const mosqueData = [
    // ==================== İSTANBUL ====================
    {
        id: 1,
        name: "Sultanahmet Camii (Mavi Cami)",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0054,
        lng: 28.9768,
        period: "Osmanlı",
        year: "1609-1616",
        architect: "Sedefkar Mehmed Ağa",
        style: "Klasik Osmanlı",
        minarets: 6,
        domes: 1,
        capacity: 10000,
        description: "Sultan I. Ahmed tarafından yaptırılan Sultanahmet Camii, altı minaresiyle dünyada benzersiz bir konuma sahiptir. İç mekanındaki mavi İznik çinileri nedeniyle 'Mavi Cami' olarak da bilinir. UNESCO Dünya Mirası Listesi'ndeki İstanbul Tarihi Alanları kapsamında koruma altındadır.",
        history: "Sultan I. Ahmed, henüz 19 yaşındayken bu camiyi yaptırmaya karar vermiştir. Altı minareli olması döneminde tartışmalara yol açmış, Mekke'deki Mescid-i Haram'a yedinci minare ekletilerek sorun çözülmüştür. Cami, Osmanlı klasik dönem mimarisinin son büyük eseri kabul edilir.",
        features: ["İznik Çinileri", "6 Minare", "UNESCO Dünya Mirası", "260 Pencere"]
    },
    {
        id: 2,
        name: "Ayasofya Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0086,
        lng: 28.9802,
        period: "Osmanlı",
        year: "537 (Cami: 1453)",
        architect: "İsidoros / Anthemios (Orijinal)",
        style: "Bizans-Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 10000,
        description: "Yaklaşık 1500 yıllık tarihiyle dünyanın en önemli mimari yapılarından biri olan Ayasofya, 537'de Bizans İmparatoru Justinianus tarafından kilise olarak inşa edilmiş, 1453'te Fatih Sultan Mehmed tarafından camiye çevrilmiştir. 2020 yılında tekrar ibadete açılmıştır.",
        history: "İlk yapı 360 yılında inşa edilmiş, yangın ve isyanlarla iki kez yıkılmıştır. Bugünkü yapı 532-537 arasında inşa edilmiştir. 916 yıl kilise, 481 yıl cami ve 86 yıl müze olarak hizmet vermiştir.",
        features: ["1500 Yıllık Tarih", "Bizans Mozaikleri", "Dev Kubbe (31m)", "UNESCO Dünya Mirası"]
    },
    {
        id: 3,
        name: "Süleymaniye Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0162,
        lng: 28.9640,
        period: "Osmanlı",
        year: "1550-1557",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 5000,
        description: "Mimar Sinan'ın 'kalfalık eserim' dediği Süleymaniye Camii, Kanuni Sultan Süleyman adına inşa edilmiştir. İstanbul'un yedi tepesinden birinin üzerinde yer alan külliye, cami, medrese, hamam, kütüphane ve hastane gibi yapıları barındırır.",
        history: "Kanuni Sultan Süleyman'ın emriyle 1550'de temeli atılmış, 7 yılda tamamlanmıştır. Külliye 22 ayrı yapıdan oluşur ve döneminin en büyük sosyal kompleksiydi.",
        features: ["Mimar Sinan Eseri", "22 Yapılı Külliye", "Akustik Mühendisliği", "Kanuni'nin Türbesi"]
    },
    {
        id: 4,
        name: "Çamlıca Camii",
        city: "İstanbul",
        district: "Üsküdar",
        lat: 41.0275,
        lng: 29.0707,
        period: "Modern",
        year: "2013-2019",
        architect: "Bahar Mızrak & Hayriye Gül Totu",
        style: "Modern Osmanlı",
        minarets: 6,
        domes: 1,
        capacity: 63000,
        description: "Türkiye'nin en büyük camii olan Çamlıca Camii, İstanbul'un Anadolu yakasında Çamlıca Tepesi'nde yer almaktadır. 63.000 kişilik kapasitesiyle Türkiye'nin ve Avrupa'nın en büyük camisi unvanını taşımaktadır.",
        history: "2013 yılında temeli atılan cami, 2019'da ibadete açılmıştır. Külliye bünyesinde müze, sanat galerisi, kütüphane ve konferans salonu da bulunmaktadır. 107.1 metre yüksekliğindeki minareleriyle İstanbul siluetinin önemli bir parçası haline gelmiştir.",
        features: ["Türkiye'nin En Büyük Camii", "63.000 Kişi Kapasitesi", "107m Minareler", "Müze ve Sanat Galerisi"]
    },
    {
        id: 5,
        name: "Eyüp Sultan Camii",
        city: "İstanbul",
        district: "Eyüpsultan",
        lat: 41.0484,
        lng: 28.9341,
        period: "Osmanlı",
        year: "1458",
        architect: "Bilinmiyor",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 4000,
        description: "İstanbul'un en kutsal mekanlarından biri olan Eyüp Sultan Camii, Hz. Muhammed'in sancaktarı Ebu Eyyub el-Ensari'nin türbesinin yanında inşa edilmiştir. İstanbul'un fethinden sonra yapılan ilk camilerden biridir.",
        history: "Fatih Sultan Mehmed, İstanbul'un fethinden 5 yıl sonra inşa ettirmiştir. Osmanlı padişahlarının kılıç kuşanma törenleri burada yapılırdı. 1798'de III. Selim tarafından yeniden yaptırılmıştır.",
        features: ["İstanbul'un En Kutsal Camisi", "Kılıç Kuşanma Törenleri", "Ebu Eyyub el-Ensari Türbesi", "Fetih Sonrası İlk Cami"]
    },
    {
        id: 6,
        name: "Yeni Cami (Eminönü)",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0053,
        lng: 28.9707,
        period: "Osmanlı",
        year: "1597-1665",
        architect: "Davut Ağa / Dalgıç Ahmed Çavuş",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 5000,
        description: "Eminönü meydanında yer alan Yeni Cami, 66 yıllık inşaat süreciyle dikkat çeker. Safiye Sultan tarafından başlatılan yapı, Turhan Hatice Sultan tarafından tamamlanmıştır. Mısır Çarşısı ile birlikte bir külliye oluşturur.",
        history: "İnşaatına 1597'de başlanmış ancak siyasi istikrarsızlıklar nedeniyle birçok kez durmuştur. 66 yıllık inşaat süreci Osmanlı tarihinin en uzun cami inşaatlarından biridir.",
        features: ["66 Yıllık İnşaat", "Mısır Çarşısı Külliyesi", "Eminönü Silüeti", "Valide Sultan Camii"]
    },
    {
        id: 7,
        name: "Ortaköy Camii (Büyük Mecidiye)",
        city: "İstanbul",
        district: "Beşiktaş",
        lat: 41.0472,
        lng: 29.0275,
        period: "Osmanlı",
        year: "1854-1856",
        architect: "Nigoğayos Balyan",
        style: "Neo-Barok",
        minarets: 2,
        domes: 1,
        capacity: 1500,
        description: "Boğaz kıyısında yer alan Ortaköy Camii, İstanbul'un en fotoğraflanan yapılarından biridir. Sultan Abdülmecid tarafından yaptırılan cami, neo-barok mimarisiyle farklı bir üslup sergiler.",
        history: "Sultan Abdülmecid tarafından eski bir caminin yerine yaptırılmıştır. Geniş pencereleri Boğaz'ın ışığını içeriye taşır. 'Su üstünde yüzen cami' olarak da anılır.",
        features: ["Boğaz Manzarası", "Neo-Barok Üslup", "Fotoğrafçıların Gözdesi", "Boğaziçi Köprüsü İle İkonik Manzara"]
    },
    {
        id: 8,
        name: "Şehzade Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0118,
        lng: 28.9563,
        period: "Osmanlı",
        year: "1543-1548",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 3000,
        description: "Mimar Sinan'ın 'çıraklık eserim' dediği Şehzade Camii, Kanuni Sultan Süleyman'ın genç yaşta ölen oğlu Şehzade Mehmed için yaptırılmıştır. Sinan'ın ilk büyük eseri olarak Osmanlı mimarisinde önemli bir yere sahiptir.",
        history: "Kanuni Sultan Süleyman, 22 yaşında ölen oğlu Şehzade Mehmed'in anısına bu camiyi yaptırmıştır. Mimar Sinan bu eseri çıraklık dönemi yapıtı olarak tanımlar.",
        features: ["Mimar Sinan'ın Çıraklık Eseri", "Şehzade Mehmed Anısına", "Simetrik Tasarım", "Renkli Taş Süslemeler"]
    },
    {
        id: 9,
        name: "Rüstem Paşa Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0164,
        lng: 28.9690,
        period: "Osmanlı",
        year: "1561-1563",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Eminönü'nde yer alan Rüstem Paşa Camii, İznik çinilerinin en yoğun kullanıldığı Osmanlı camilerinden biridir. Kanuni'nin damadı Rüstem Paşa adına Mimar Sinan tarafından inşa edilmiştir.",
        history: "Caminin iç duvarları tamamen İznik çinileriyle kaplıdır. Çini süslemelerin zenginliği ve çeşitliliğiyle Osmanlı sanatının şaheserlerinden biridir.",
        features: ["İznik Çinileri", "Mimar Sinan Eseri", "Yükseltilmiş Platform", "Lale Motifleri"]
    },
    {
        id: 10,
        name: "Mihrimah Sultan Camii (Edirnekapı)",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0283,
        lng: 28.9393,
        period: "Osmanlı",
        year: "1562-1565",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Mimar Sinan'ın Kanuni'nin kızı Mihrimah Sultan için yaptığı camilerden biri olan Edirnekapı Mihrimah Sultan Camii, İstanbul'un en yüksek noktasında yer alır. 161 penceresiyle 'ışık camisi' olarak bilinir.",
        history: "Kanuni Sultan Süleyman'ın kızı Mihrimah Sultan için yapılmıştır. Mimar Sinan'ın Mihrimah Sultan'a duyduğu platonik aşkın simgesi olarak da anlatılır.",
        features: ["161 Pencere", "Işık Camisi", "İstanbul'un En Yüksek Noktası", "Mimar Sinan'ın Aşk Eseri"]
    },
    {
        id: 11,
        name: "Beyazıt Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0105,
        lng: 28.9646,
        period: "Osmanlı",
        year: "1500-1506",
        architect: "Yakub Şah bin Sultan Şah",
        style: "Erken Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 4000,
        description: "İstanbul'daki en eski ayakta kalan padişah camisi olan Beyazıt Camii, II. Bayezid tarafından yaptırılmıştır. Osmanlı mimarisinde erken klasik dönemin önemli bir eseridir.",
        history: "Sultan II. Bayezid'in emriyle 1500-1506 yılları arasında inşa edilmiştir. Osmanlı klasik mimarisinin temellerini atmıştır.",
        features: ["İstanbul'un En Eski Sultan Camisi", "Erken Klasik Dönem", "Beyazıt Meydanı"]
    },
    {
        id: 12,
        name: "Fatih Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0198,
        lng: 28.9499,
        period: "Osmanlı",
        year: "1463-1470 (Yeniden: 1767-1771)",
        architect: "Atik Sinan / Mehmed Tahir Ağa",
        style: "Klasik Osmanlı / Barok",
        minarets: 2,
        domes: 1,
        capacity: 10000,
        description: "Fatih Sultan Mehmed tarafından İstanbul'un fethinden sonra yaptırılan ilk büyük külliye olan Fatih Camii, 1766 depreminde yıkılmış ve III. Mustafa döneminde yeniden inşa edilmiştir.",
        history: "İstanbul'un fethinden sonra inşa edilen ilk büyük padişah külliyesidir. Orijinal yapı 1766 depreminde ağır hasar görmüş, barok üslupta yeniden inşa edilmiştir. Fatih Sultan Mehmed'in türbesi burada bulunmaktadır.",
        features: ["Fatih Sultan Mehmed Türbesi", "İstanbul'un İlk Büyük Külliyesi", "Deprem Sonrası Yeniden İnşa", "8 Medrese"]
    },
    {
        id: 13,
        name: "Nuruosmaniye Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0098,
        lng: 28.9710,
        period: "Osmanlı",
        year: "1748-1755",
        architect: "Simeon Kalfa / Mustafa Ağa",
        style: "Osmanlı Barok",
        minarets: 2,
        domes: 1,
        capacity: 3000,
        description: "İstanbul'un ilk barok üsluplu camisi olan Nuruosmaniye Camii, Kapalıçarşı'nın hemen yanında yer almaktadır. Sultan I. Mahmud döneminde başlanıp III. Osman döneminde tamamlanmıştır.",
        history: "Osmanlı mimarisinde barok akımın ilk büyük eseri olarak kabul edilir. Yarım daire avlusu Osmanlı mimarisinde benzersizdir.",
        features: ["İlk Barok Cami", "Kapalıçarşı Yanında", "Yarım Daire Avlu", "Osmanlı Barok Akımı"]
    },
    {
        id: 14,
        name: "Dolmabahçe Camii (Bezm-i Alem Valide Sultan)",
        city: "İstanbul",
        district: "Beşiktaş",
        lat: 41.0390,
        lng: 29.0005,
        period: "Osmanlı",
        year: "1853-1855",
        architect: "Nigoğayos Balyan",
        style: "Barok-Ampir",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Dolmabahçe Sarayı'nın hemen yanında, Boğaz kıyısında yer alan zarif cami. Bezm-i Alem Valide Sultan tarafından yaptırılmıştır. Barok ve ampir üsluplarını harmanlayan mimarisiyle dikkat çeker.",
        history: "Sultan Abdülmecid'in annesi Bezm-i Alem Valide Sultan tarafından yaptırılmıştır. Dolmabahçe Sarayı kompleksinin bir parçasıdır.",
        features: ["Dolmabahçe Sarayı Yanında", "Boğaz Kıyısı", "Barok-Ampir Üslup", "Valide Sultan Camii"]
    },
    {
        id: 15,
        name: "Sokullu Mehmed Paşa Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0028,
        lng: 28.9741,
        period: "Osmanlı",
        year: "1571-1572",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Mimar Sinan'ın olgunluk dönemi eserlerinden biri olan Sokullu Mehmed Paşa Camii, eğimli araziye ustaca yerleştirilmiş planıyla ve İznik çinileriyle ünlüdür. Kabe taşı parçalarının mihrap, minber ve kapıya yerleştirilmesiyle dikkat çeker.",
        history: "Sadrazam Sokullu Mehmed Paşa'nın eşi Esmahan Sultan tarafından yaptırılmıştır. 4 adet Kabe taşı (Hacer-ül Esved) parçası yapının farklı noktalarına yerleştirilmiştir.",
        features: ["Mimar Sinan Eseri", "4 Kabe Taşı Parçası", "İznik Çinileri", "Eğimli Arazi Çözümü"]
    },
    {
        id: 16,
        name: "Pertevniyal Valide Sultan Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0093,
        lng: 28.9512,
        period: "Osmanlı",
        year: "1869-1871",
        architect: "Montani Efendi",
        style: "Eklektik (Gotik-Osmanlı)",
        minarets: 2,
        domes: 1,
        capacity: 1500,
        description: "Aksaray'da yer alan Pertevniyal Valide Sultan Camii, Gotik, Rönesans ve Osmanlı üsluplarını bir arada barındıran nadir yapılardan biridir. Sultan Abdülaziz'in annesi Pertevniyal Sultan tarafından yaptırılmıştır.",
        history: "Osmanlı'nın son dönemlerinde Batı etkisindeki eklektik mimarinin dini yapılara yansımasının en belirgin örneğidir.",
        features: ["Gotik-Osmanlı Karışımı", "Eklektik Mimari", "Aksaray Meydanı", "Son Dönem Osmanlı"]
    },
    {
        id: 17,
        name: "Küçük Ayasofya Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0019,
        lng: 28.9726,
        period: "Osmanlı",
        year: "527-536 (Cami: 16. yy)",
        architect: "İsidoros / Anthemios (Orijinal)",
        style: "Bizans-Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Aslen Aziz Sergius ve Bacchus Kilisesi olarak inşa edilen yapı, Ayasofya'nın küçük bir modeli gibi tasarlanmıştır. Osmanlı döneminde camiye çevrilmiştir.",
        history: "Justinianus döneminde inşa edilmiş, Ayasofya'dan önce yapılmıştır. Osmanlı döneminde Hüseyin Ağa tarafından camiye çevrilmiştir.",
        features: ["Bizans Dönemi", "Ayasofya'nın Küçük Modeli", "Sekizgen Plan", "1500 Yıllık Yapı"]
    },
    {
        id: 18,
        name: "Laleli Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0083,
        lng: 28.9575,
        period: "Osmanlı",
        year: "1760-1763",
        architect: "Mehmed Tahir Ağa",
        style: "Osmanlı Barok",
        minarets: 2,
        domes: 1,
        capacity: 3000,
        description: "Sultan III. Mustafa tarafından yaptırılan Laleli Camii, Osmanlı barok mimarisinin önemli eserlerinden biridir. Altında çarşı ve dükkanlar bulunan yükseltilmiş platformu ile dikkat çeker.",
        history: "Rivayete göre Sultan III. Mustafa rüyasında bir derviş gördükten sonra camiyi yaptırmaya karar vermiştir. Altındaki dükkanlardan elde edilen gelir caminin bakımı için vakfedilmiştir.",
        features: ["Osmanlı Barok", "Yükseltilmiş Platform", "Altında Çarşı", "III. Mustafa Dönemi"]
    },

    // ==================== ANKARA ====================
    {
        id: 19,
        name: "Kocatepe Camii",
        city: "Ankara",
        district: "Çankaya",
        lat: 39.9199,
        lng: 32.8543,
        period: "Modern",
        year: "1967-1987",
        architect: "Hüsrev Tayla & Fatin Uluengin",
        style: "Neo-Klasik Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 24000,
        description: "Ankara'nın en büyük camii olan Kocatepe Camii, Cumhuriyet döneminin en önemli dini yapılarından biridir. Klasik Osmanlı mimarisi tarzında inşa edilmiş olup, altında bir alışveriş merkezi ve otopark bulunmaktadır.",
        history: "1944 yılında projeye başlanmıştır. İlk modern tasarım projeleri terk edilerek, klasik Osmanlı üslubunda inşa edilmiştir. 20 yıllık inşaat sürecinin ardından 1987'de ibadete açılmıştır.",
        features: ["Ankara'nın En Büyük Camii", "24.000 Kişi Kapasitesi", "Alışveriş Merkezi Altında", "88m Minareler"]
    },
    {
        id: 20,
        name: "Hacı Bayram Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9413,
        lng: 32.8637,
        period: "Osmanlı",
        year: "1427-1428",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "Ankara'nın en eski ve en kutsal camilerinden biri olan Hacı Bayram Camii, Hacı Bayram-ı Veli tarafından yaptırılmıştır. Augustus Tapınağı'na bitişik konumuyla farklı medeniyetlerin bir arada bulunduğu tarihi bir mekandır.",
        history: "Bayramiye tarikatının kurucusu Hacı Bayram-ı Veli adına 15. yüzyılda inşa edilmiştir. Roma dönemine ait Augustus Tapınağı yer almaktadır.",
        features: ["Augustus Tapınağı Yanında", "Hacı Bayram-ı Veli Türbesi", "Ahşap Tavan", "Çini Süslemeler"]
    },
    {
        id: 21,
        name: "Cenabi Ahmet Paşa Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9350,
        lng: 32.8550,
        period: "Osmanlı",
        year: "1565-1566",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Mimar Sinan'ın Ankara'daki tek eseri olan Cenabi Ahmet Paşa Camii, klasik Osmanlı mimarisinin başkentteki en güzel örneklerinden biridir. Altıgen planlı yapısıyla dikkat çeker.",
        history: "Beylerbeyisi Cenabi Ahmet Paşa tarafından Mimar Sinan'a yaptırılmıştır. Altıgen plan şeması Osmanlı mimarisinde nadir görülen bir uygulamadır.",
        features: ["Mimar Sinan Eseri", "Altıgen Plan", "Ankara'daki Tek Sinan Eseri"]
    },
    {
        id: 22,
        name: "Arslanhane Camii (Ahi Şerafeddin)",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9380,
        lng: 32.8587,
        period: "Selçuklu",
        year: "1289-1290",
        architect: "Bilinmiyor",
        style: "Anadolu Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 800,
        description: "Ankara'nın en eski camilerinden olan Arslanhane Camii, kapısındaki aslan kabartmasından ismini almıştır. Selçuklu ahşap direkli cami geleneğinin Ankara'daki en güzel örneğidir. 24 ahşap sütun üzerindeki düz çatısıyla dikkat çeker.",
        history: "13. yüzyılda Ahi Şerafettin tarafından inşa ettirilmiştir. Kapısındaki aslan kabartması nedeniyle Arslanhane adıyla anılmaktadır.",
        features: ["Aslan Kabartması", "24 Ahşap Sütun", "Selçuklu Ahşap Geleneği", "Ankara'nın En Eski Camisi"]
    },
    {
        id: 23,
        name: "Ahi Elvan Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9375,
        lng: 32.8600,
        period: "Osmanlı",
        year: "1382",
        architect: "Bilinmiyor",
        style: "Ahi Geleneği / Erken Osmanlı",
        minarets: 1,
        domes: 0,
        capacity: 500,
        description: "Ankara'nın tarihi kalesi yakınında yer alan Ahi Elvan Camii, Ahi teşkilatının Ankara'daki önemini yansıtan bir yapıdır. Ahşap sütunları ve tavan süslemeleriyle dikkat çeker.",
        history: "Ahi Elvan Mehmed Bey tarafından inşa ettirilmiştir. Ahilik geleneğinin Ankara'daki merkezlerinden biri olmuştur.",
        features: ["Ahi Teşkilatı", "Ahşap Sütunlar", "Ankara Kalesi Yakınında", "14. Yüzyıl"]
    },
    {
        id: 24,
        name: "Aslanhane Camii Yanı - Alaaddin Camii (Ankara)",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9386,
        lng: 32.8575,
        period: "Selçuklu",
        year: "1178",
        architect: "Bilinmiyor",
        style: "Anadolu Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 600,
        description: "Ankara Kalesi eteklerinde yer alan Alaaddin Camii, Anadolu Selçuklu döneminin Ankara'daki önemli eserlerindendir. Ahşap tavanlı ve düz çatılı yapısıyla Selçuklu cami geleneğini yansıtır.",
        history: "12. yüzyılda Anadolu Selçuklu döneminde inşa edilmiştir. Ankara'nın en eski ibadet mekanlarından biridir.",
        features: ["12. Yüzyıl", "Ankara Kalesi Etekleri", "Selçuklu Dönemi", "Ahşap Tavan"]
    },
    {
        id: 25,
        name: "Melike Hatun Camii (Ankara)",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9330,
        lng: 32.8610,
        period: "Osmanlı",
        year: "2020",
        architect: "Bilinmiyor",
        style: "Modern Osmanlı-Selçuklu",
        minarets: 4,
        domes: 1,
        capacity: 15000,
        description: "Ankara'nın en yeni büyük camilerinden biri olan Melike Hatun Camii, Kızılay yakınında yer almaktadır. Selçuklu ve Osmanlı mimarisinin modern yorumlarını bir araya getirmektedir.",
        history: "2020 yılında ibadete açılmıştır. Ankara'nın merkezinde modern mimarisiyle dikkat çekmektedir.",
        features: ["Modern Tasarım", "15.000 Kişi Kapasitesi", "Kızılay Yakınında", "Selçuklu-Osmanlı Yorumu"]
    },
    {
        id: 26,
        name: "Ahmet Hamdi Akseki Camii",
        city: "Ankara",
        district: "Yenimahalle",
        lat: 39.9600,
        lng: 32.8100,
        period: "Modern",
        year: "2013",
        architect: "Bilinmiyor",
        style: "Modern",
        minarets: 2,
        domes: 1,
        capacity: 6000,
        description: "Ankara'nın batı yakasında yer alan büyük ve modern bir cami. Diyanet İşleri Başkanlığı yerleşkesine yakın konumda yer almaktadır.",
        history: "2013 yılında ibadete açılmıştır. Ankara'nın modern camilerinden biri olarak öne çıkmaktadır.",
        features: ["Modern Mimari", "Geniş İç Mekan", "Yenimahalle"]
    },
    {
        id: 27,
        name: "Karacabey Camii (Ankara)",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9390,
        lng: 32.8640,
        period: "Osmanlı",
        year: "1427-1440",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Hacı Bayram Camii yakınında yer alan Karacabey Camii, Osmanlı'nın erken döneminden kalan önemli bir külliye yapısıdır. Hamam, medrese ve imaretten oluşan külliyesiyle dikkat çeker.",
        history: "Karacabey bin Abdullah tarafından 15. yüzyılda inşa ettirilmiştir. Ankara'nın en önemli Osmanlı külliyelerinden biridir.",
        features: ["Erken Osmanlı Külliyesi", "Hamam ve Medrese", "Hacı Bayram Yakını"]
    },
    {
        id: 28,
        name: "Zincirli Camii (Ankara)",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9365,
        lng: 32.8620,
        period: "Osmanlı",
        year: "15. yüzyıl",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 0,
        capacity: 400,
        description: "Ankara'nın tarihi Ulus semtinde yer alan Zincirli Camii, avlu kapısındaki zincirden ismini almıştır. Bu zincir, içeriye girerken eğilmeyi ve tevazu göstermeyi simgelemektedir.",
        history: "15. yüzyılda inşa edildiği kabul edilmektedir. Kapısındaki zincir geleneği birçok Osmanlı camisinde görülen bir uygulamadır.",
        features: ["Zincirli Kapı", "Tevazu Simgesi", "Ulus Semtinde", "15. Yüzyıl"]
    },
    {
        id: 29,
        name: "Yeni Cami (Ankara)",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9370,
        lng: 32.8555,
        period: "Osmanlı",
        year: "1565",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 800,
        description: "Ankara'nın Samanpazarı bölgesinde yer alan Yeni Cami, Osmanlı döneminin önemli eserlerinden biridir. Çarşı bölgesinde konumlanmış olup esnaf tarafından yoğun olarak kullanılmıştır.",
        history: "16. yüzyılda inşa edilmiştir. Ankara'nın ticaret merkezinde yer alması nedeniyle 'çarşı camisi' olarak da anılmıştır.",
        features: ["Samanpazarı", "Çarşı Camisi", "16. Yüzyıl"]
    },
    {
        id: 30,
        name: "Örtmeli (Örtülü) Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9395,
        lng: 32.8580,
        period: "Selçuklu",
        year: "13. yüzyıl",
        architect: "Bilinmiyor",
        style: "Anadolu Selçuklu",
        minarets: 0,
        domes: 0,
        capacity: 300,
        description: "Ankara Kalesi içinde yer alan Örtmeli Camii, Selçuklu dönemine ait küçük ama tarihi açıdan çok değerli bir yapıdır. Ahşap örtü sistemiyle dikkat çeker.",
        history: "13. yüzyılda inşa edildiği kabul edilmektedir. Ankara Kalesi'nin iç kalesinde yer almaktadır.",
        features: ["Ankara Kalesi İçinde", "Selçuklu Dönemi", "Ahşap Örtü", "13. Yüzyıl"]
    },
    {
        id: 31,
        name: "Taceddin Sultan Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9345,
        lng: 32.8530,
        period: "Cumhuriyet",
        year: "1928 (Kurtuluş Savaşı Karargahı)",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Kurtuluş Savaşı sırasında Mustafa Kemal Atatürk'ün karargah olarak kullandığı tarihi cami. I. Meclis'e yakın konumuyla Milli Mücadele döneminin önemli yapılarından biridir. Bugün Kurtuluş Savaşı Müzesi olarak da hizmet vermektedir.",
        history: "Atatürk, Ankara'ya geldiğinde bu caminin yanındaki medrese odalarını karargah olarak kullanmıştır. Milli Mücadele tarihinin simge yapılarından biridir.",
        features: ["Atatürk Karargahı", "Kurtuluş Savaşı Tarihi", "I. Meclis Yakını", "Müze"]
    },
    {
        id: 32,
        name: "Maltepe Camii",
        city: "Ankara",
        district: "Çankaya",
        lat: 39.9250,
        lng: 32.8420,
        period: "Cumhuriyet",
        year: "1957",
        architect: "Bilinmiyor",
        style: "Cumhuriyet Dönemi",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Ankara'nın Maltepe semtinde yer alan ve Cumhuriyet döneminin mimari anlayışını yansıtan bir cami. Sade ve işlevsel tasarımıyla dikkat çeker.",
        history: "1957 yılında hizmete açılmıştır. Ankara'nın Cumhuriyet dönemi cami mimarisinin örneklerinden biridir.",
        features: ["Cumhuriyet Dönemi", "Sade Mimari", "Maltepe Semti"]
    },
    {
        id: 33,
        name: "Beştepe Millet Camii",
        city: "Ankara",
        district: "Yenimahalle",
        lat: 39.9310,
        lng: 32.7990,
        period: "Modern",
        year: "2015",
        architect: "Bilinmiyor",
        style: "Modern Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 5000,
        description: "Cumhurbaşkanlığı Külliyesi bünyesinde yer alan Beştepe Millet Camii, modern Osmanlı-Selçuklu mimarisini yansıtan çağdaş bir yapıdır.",
        history: "2015 yılında Cumhurbaşkanlığı Külliyesi ile birlikte hizmete açılmıştır.",
        features: ["Cumhurbaşkanlığı Külliyesi", "Modern Tasarım", "Osmanlı-Selçuklu Esinli"]
    },

    // ==================== EDİRNE ====================
    {
        id: 34,
        name: "Selimiye Camii",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6789,
        lng: 26.5590,
        period: "Osmanlı",
        year: "1568-1574",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 6000,
        description: "Mimar Sinan'ın 'ustalık eserim' dediği Selimiye Camii, Osmanlı mimarisinin en büyük başyapıtlarından biridir. 31.28 metre çapındaki kubbesiyle Ayasofya'yı geçmeyi başarmıştır. 2011 yılında UNESCO Dünya Mirası Listesi'ne alınmıştır.",
        history: "Sultan II. Selim'in emriyle yapılmıştır. Mimar Sinan, 80 yaşını aşkın iken bu camiyi tasarlamış ve 'ustalık eserim' olarak nitelendirmiştir.",
        features: ["Mimar Sinan'ın Ustalık Eseri", "31.28m Kubbe", "UNESCO Dünya Mirası", "71.5m Minareler"]
    },
    {
        id: 35,
        name: "Eski Cami (Edirne)",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6770,
        lng: 26.5560,
        period: "Osmanlı",
        year: "1403-1414",
        architect: "Konyalı Hacı Alaaddin",
        style: "Erken Osmanlı",
        minarets: 2,
        domes: 9,
        capacity: 3000,
        description: "Edirne'nin en eski camisi olan Eski Cami, 9 kubbeli yapısı ve devasa hat yazılarıyla dikkat çeker. Bursa Ulu Cami'nin bir devamı niteliğindedir.",
        history: "Fetret Devri'nde başlanan yapı, I. Mehmed döneminde tamamlanmıştır. Duvarlarındaki dev hat yazıları çok etkileyicidir.",
        features: ["9 Kubbe", "Dev Hat Yazıları", "Edirne'nin En Eski Camisi", "Fetret Devri Eseri"]
    },
    {
        id: 36,
        name: "Üç Şerefeli Cami",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6785,
        lng: 26.5557,
        period: "Osmanlı",
        year: "1437-1447",
        architect: "Bilinmiyor",
        style: "Geçiş Dönemi Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 3000,
        description: "Osmanlı mimarisinde tek kubbeli cami geleneğini başlatan Üç Şerefeli Cami, II. Murad tarafından yaptırılmıştır. Dört minaresi birbirinden farklı tasarımdadır.",
        history: "II. Murad'ın emriyle 10 yılda inşa edilmiştir. Osmanlı mimarisinde çok kubbeli yapıdan tek kubbeye geçişin ilk örneğidir.",
        features: ["3 Şerefeli Minare", "Tek Kubbe Geleneğinin Başlangıcı", "4 Farklı Minare", "Geçiş Dönemi Eseri"]
    },
    {
        id: 37,
        name: "Muradiye Camii (Edirne)",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6815,
        lng: 26.5620,
        period: "Osmanlı",
        year: "1435",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "II. Murad tarafından yaptırılan Muradiye Camii, özellikle çini süslemeleriyle ünlüdür. Edirne'nin en güzel çinili camilerinden biridir.",
        history: "II. Murad döneminde Mevlevi dergahı olarak da kullanılmak üzere inşa edilmiştir.",
        features: ["Çini Süslemeler", "Mevlevi Dergahı", "II. Murad Dönemi"]
    },
    {
        id: 38,
        name: "II. Bayezid Külliyesi Camii (Edirne)",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6840,
        lng: 26.5450,
        period: "Osmanlı",
        year: "1484-1488",
        architect: "Hayreddin",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 3000,
        description: "Sultan II. Bayezid tarafından Tunca Nehri kıyısında inşa ettirilen külliye, cami, darüşşifa (hastane), medrese, imaret ve hamamdan oluşur. Darüşşifası müzik ile tedavi yapılan dünyanın ilk sağlık komplekslerinden biridir.",
        history: "Külliyedeki darüşşifada akıl hastalarına müzik ve su sesiyle tedavi uygulanmıştır. Bu yöntem dönemin çok ötesinde bir anlayışı yansıtmaktadır.",
        features: ["Darüşşifa (Hastane)", "Müzikle Tedavi", "Tunca Nehri Kıyısı", "UNESCO Geçici Liste"]
    },

    // ==================== BURSA ====================
    {
        id: 39,
        name: "Ulu Cami (Bursa)",
        city: "Bursa",
        district: "Osmangazi",
        lat: 40.1837,
        lng: 29.0597,
        period: "Osmanlı",
        year: "1396-1400",
        architect: "Ali Neccar",
        style: "Erken Osmanlı",
        minarets: 2,
        domes: 20,
        capacity: 5000,
        description: "Bursa Ulu Cami, 20 kubbesiyle Osmanlı mimarisinin en önemli erken dönem eserlerinden biridir. Yıldırım Bayezid tarafından Niğbolu Zaferi'nin ardından yaptırılmıştır.",
        history: "Yıldırım Bayezid, Niğbolu Savaşı öncesi zafer kazanırsa 20 cami yaptıracağına söz vermiştir. 20 ayrı cami yerine 20 kubbeli tek bir cami inşa ettirmiştir. 192 hat levhası bulunmaktadır.",
        features: ["20 Kubbe", "192 Hat Levhası", "İç Şadırvan", "Niğbolu Zaferi Hediyesi"]
    },
    {
        id: 40,
        name: "Yeşil Cami (Bursa)",
        city: "Bursa",
        district: "Yıldırım",
        lat: 40.1787,
        lng: 29.0699,
        period: "Osmanlı",
        year: "1419-1421",
        architect: "Hacı İvaz Paşa",
        style: "Erken Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 2000,
        description: "Sultan I. Mehmed tarafından yaptırılan Yeşil Cami, içindeki yeşil ve mavi tonlarındaki çinileriyle ünlüdür. Osmanlı çini sanatının en güzel örneklerini barındırır.",
        history: "Çelebi Sultan Mehmed tarafından yaptırılmıştır. Mihrabı Osmanlı çini sanatının başyapıtı kabul edilir.",
        features: ["Yeşil Çiniler", "Osmanlı Çini Sanatı", "Sultan Locası", "Yeşil Türbe Yanında"]
    },
    {
        id: 41,
        name: "Hüdavendigar (Muradiye) Camii",
        city: "Bursa",
        district: "Osmangazi",
        lat: 40.1930,
        lng: 29.0175,
        period: "Osmanlı",
        year: "1365-1385",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Sultan I. Murad tarafından yaptırılan bu yapı, alt katı cami, üst katı medrese olan dünyada eşsiz bir tasarıma sahiptir. Çekirge semtinde termal bölgede yer alır.",
        history: "Alt katı cami, üst katı medrese olan iki katlı yapısıyla dünyada tek örnektir. Ters T planlı ilk Osmanlı camilerinden biridir.",
        features: ["İki Katlı Cami-Medrese", "Dünyada Tek Örnek", "Ters T Plan", "Çekirge Semtinde"]
    },
    {
        id: 42,
        name: "Muradiye Camii (Bursa)",
        city: "Bursa",
        district: "Osmangazi",
        lat: 40.1895,
        lng: 29.0505,
        period: "Osmanlı",
        year: "1426",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "II. Murad tarafından yaptırılan Muradiye Camii, çevresindeki 12 türbe ile birlikte Osmanlı sultanlarının gömülü olduğu önemli bir mezarlık alanı oluşturur. Çini süslemeleriyle dikkat çeker.",
        history: "II. Murad'ın yaptırdığı son büyük eserdir. Çevresinde Osmanlı şehzade ve sultanlarına ait 12 türbe bulunmaktadır.",
        features: ["12 Osmanlı Türbesi", "Çini Süslemeler", "Sultan Mezarlığı", "II. Murad Dönemi"]
    },
    {
        id: 43,
        name: "Orhan Gazi Camii (Bursa)",
        city: "Bursa",
        district: "Osmangazi",
        lat: 40.1850,
        lng: 29.0585,
        period: "Osmanlı",
        year: "1339",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Bursa'nın fethinden sonra Orhan Gazi tarafından yaptırılan bu cami, Osmanlı İmparatorluğu'nun ilk camilerinden biridir. Osmanlı mimari geleneğinin temellerinin atıldığı yapıdır.",
        history: "1326'da Bursa'nın fethinin ardından Orhan Gazi tarafından inşa ettirilmiştir. Osmanlı'nın ilk büyük cami yapılarından biridir.",
        features: ["Osmanlı'nın İlk Camilerinden", "Orhan Gazi Dönemi", "1339", "Bursa Çarşısı Yanında"]
    },
    {
        id: 44,
        name: "Emir Sultan Camii (Bursa)",
        city: "Bursa",
        district: "Yıldırım",
        lat: 40.1760,
        lng: 29.0750,
        period: "Osmanlı",
        year: "1804 (Yeniden İnşa)",
        architect: "Bilinmiyor",
        style: "Osmanlı Barok",
        minarets: 2,
        domes: 1,
        capacity: 2500,
        description: "Emir Sultan'ın türbesinin yanında yer alan cami, Bursa'nın en çok ziyaret edilen dini mekanlarından biridir. Yüzyıllar boyunca birçok kez yeniden inşa edilmiştir.",
        history: "İlk olarak Yıldırım Bayezid döneminde inşa edilmiş, depremler nedeniyle birçok kez yeniden yapılmıştır. Bugünkü yapı III. Selim döneminde inşa edilmiştir.",
        features: ["Emir Sultan Türbesi", "Barok Üslup", "Bursa Manzarası", "Ziyaret Mekanı"]
    },

    // ==================== KONYA ====================
    {
        id: 45,
        name: "Mevlana Müzesi ve Camii",
        city: "Konya",
        district: "Karatay",
        lat: 37.8714,
        lng: 32.5044,
        period: "Selçuklu",
        year: "1274",
        architect: "Bedreddin Tebrizli",
        style: "Selçuklu",
        minarets: 0,
        domes: 1,
        capacity: 2000,
        description: "Mevlana Celaleddin-i Rumi'nin türbesinin bulunduğu yapı, yeşil çinili kubbesiyle Konya'nın simgesidir. Mevlevi dergahı olarak da kullanılan yapı, bugün hem müze hem de ibadet mekanı olarak hizmet vermektedir.",
        history: "Mevlana'nın 1273'te vefatının ardından türbesi üzerine inşa edilmiştir. Yüzyıllar boyunca Mevlevi tarikatının merkezi olmuştur.",
        features: ["Yeşil Kubbe", "Mevlana Türbesi", "Sema Gösterileri", "Selçuklu Mimarisi"]
    },
    {
        id: 46,
        name: "Alaaddin Camii (Konya)",
        city: "Konya",
        district: "Karatay",
        lat: 37.8739,
        lng: 32.4922,
        period: "Selçuklu",
        year: "1155-1220",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Konya'nın merkezinde, Alaaddin Tepesi üzerinde yer alan bu cami, Anadolu Selçuklu Devleti'nin en önemli dini yapılarından biridir. 8 Selçuklu sultanının türbesi burada bulunmaktadır.",
        history: "I. Mesud döneminde inşasına başlanmış, I. Alaaddin Keykubad döneminde tamamlanmıştır. Selçuklu sarayının yanında yer alan devletin resmi camisiydi.",
        features: ["Selçuklu Sarayı Yanında", "8 Sultan Türbesi", "Minber (1155)", "Anadolu'nun En Eski Camilerinden"]
    },
    {
        id: 47,
        name: "Aziziye Camii (Konya)",
        city: "Konya",
        district: "Karatay",
        lat: 37.8699,
        lng: 32.4977,
        period: "Osmanlı",
        year: "1874",
        architect: "Bilinmiyor",
        style: "Barok-Rokoko",
        minarets: 2,
        domes: 1,
        capacity: 1500,
        description: "Konya'nın merkezinde yer alan Aziziye Camii, Osmanlı barok ve rokoko stilinin Anadolu'daki nadir örneklerinden biridir. Gotik ve barok öğelerin harmanlandığı eşsiz bir mimari tarz sergiler.",
        history: "Sultan Abdülaziz döneminde inşa edilmiştir. İki kez yanan cami, üçüncü kez bugünkü haliyle yeniden yapılmıştır.",
        features: ["Barok-Rokoko Üslup", "Gotik Öğeler", "Çifte Minare", "Üç Kez İnşa Edilmiş"]
    },
    {
        id: 48,
        name: "İplikçi Camii (Konya)",
        city: "Konya",
        district: "Karatay",
        lat: 37.8725,
        lng: 32.4970,
        period: "Selçuklu",
        year: "1201-1202",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "Konya'nın en eski camilerinden biri olan İplikçi Camii, Anadolu Selçuklu dönemine ait önemli bir eserdir. Mevlana'nın sohbetlerini yaptığı cami olarak bilinmektedir.",
        history: "Anadolu Selçuklu Veziri Şemseddin Altunaba tarafından yaptırılmıştır. Mevlana Celaleddin-i Rumi'nin sohbetlerini yaptığı ve vaaz verdiği yer olarak bilinir.",
        features: ["Mevlana'nın Sohbet Ettiği Cami", "Selçuklu Dönemi", "1201 Yapım Yılı"]
    },
    {
        id: 49,
        name: "Eşrefoğlu Camii (Beyşehir)",
        city: "Konya",
        district: "Beyşehir",
        lat: 37.6780,
        lng: 31.7260,
        period: "Selçuklu",
        year: "1296-1299",
        architect: "Bilinmiyor",
        style: "Anadolu Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "UNESCO Dünya Mirası Listesi'ndeki Anadolu Selçuklu ahşap direkli camilerinden biri olan Eşrefoğlu Camii, ahşap sütunları ve çini süslemeleriyle Beyşehir'in en önemli yapısıdır.",
        history: "Eşrefoğlu Süleyman Bey tarafından yaptırılmıştır. 2013 yılında UNESCO Dünya Mirası Listesi'ne dahil edilmiştir.",
        features: ["UNESCO Dünya Mirası", "Ahşap Sütunlar", "42 Ağaç Direk", "Çini Mihrap"]
    },
    {
        id: 50,
        name: "Selimiye Camii (Konya)",
        city: "Konya",
        district: "Selçuklu",
        lat: 37.8740,
        lng: 32.4960,
        period: "Osmanlı",
        year: "1558",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Sultan II. Selim'in şehzadeliği döneminde Konya valisi iken yaptırdığı cami. Mevlana Müzesi'ne yakın konumuyla dikkat çeker.",
        history: "II. Selim henüz şehzade iken Konya valisi olduğu dönemde inşa ettirmiştir.",
        features: ["Şehzade II. Selim Dönemi", "Mevlana Müzesi Yakını", "Osmanlı Klasik"]
    },

    // ==================== İZMİR ====================
    {
        id: 51,
        name: "Hisar Camii",
        city: "İzmir",
        district: "Konak",
        lat: 38.4199,
        lng: 27.1289,
        period: "Osmanlı",
        year: "1597",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "İzmir'in en büyük ve en eski Osmanlı camisi olan Hisar Camii, Kemeralti çarşısı içinde yer almaktadır. Osmanlı barok üslubundaki süslemeleri ve geniş iç mekanıyla dikkat çeker.",
        history: "16. yüzyıl sonlarında inşa edilmiştir. İzmir'in en önemli Osmanlı dönemi eseri olarak kabul edilmektedir.",
        features: ["İzmir'in En Büyük Camii", "Kemeralti Çarşısı İçinde", "Barok Süslemeler", "Tarihi Vaaz Kürsüsü"]
    },
    {
        id: 52,
        name: "İsa Bey Camii",
        city: "İzmir",
        district: "Selçuk",
        lat: 37.9425,
        lng: 27.3697,
        period: "Selçuklu",
        year: "1374-1375",
        architect: "Şamlı Ali bin Dımışki",
        style: "Aydınoğulları / Beylikler",
        minarets: 2,
        domes: 2,
        capacity: 2000,
        description: "Efes antik kenti yakınında yer alan İsa Bey Camii, Aydınoğulları Beyliği dönemine ait önemli bir eserdir. Artemis Tapınağı'nın sütunları kullanılarak inşa edilmiştir.",
        history: "Aydınoğlu İsa Bey tarafından 1375'te yaptırılmıştır. Efes'teki Artemis Tapınağı'ndan devşirme malzemeler kullanılmıştır.",
        features: ["Efes Yakınında", "Artemis Tapınağı Sütunları", "Beylikler Dönemi", "Avlulu Cami Planı"]
    },
    {
        id: 53,
        name: "Kestanepazarı Camii (İzmir)",
        city: "İzmir",
        district: "Konak",
        lat: 38.4185,
        lng: 27.1300,
        period: "Osmanlı",
        year: "1663",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Kemeralti'nın tarihi dokusunda yer alan Kestanepazarı Camii, İzmir'in önemli Osmanlı dönemi camilerinden biridir.",
        history: "17. yüzyılda inşa edilmiştir. Kemeralti çarşı bölgesinin önemli yapılarından biridir.",
        features: ["Kemeralti Çarşısı", "17. Yüzyıl", "Osmanlı Dönemi"]
    },
    {
        id: 54,
        name: "Salepçioğlu Camii (İzmir)",
        city: "İzmir",
        district: "Konak",
        lat: 38.4195,
        lng: 27.1280,
        period: "Osmanlı",
        year: "1905",
        architect: "Bilinmiyor",
        style: "Geç Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "İzmir'in Konak meydanı yakınında yer alan Salepçioğlu Camii, Osmanlı'nın son dönem eserlerinden biridir. Dış cephesindeki saat kulesi görünümlü minaresiyle dikkat çeker.",
        history: "20. yüzyıl başında Salepçioğlu ailesi tarafından yaptırılmıştır.",
        features: ["Konak Meydanı Yakını", "Geç Osmanlı Dönemi", "Saat Kulesi Minaresi"]
    },

    // ==================== ANTALYA ====================
    {
        id: 55,
        name: "Yivli Minare Camii",
        city: "Antalya",
        district: "Muratpaşa",
        lat: 36.8856,
        lng: 30.7068,
        period: "Selçuklu",
        year: "1230",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 6,
        capacity: 1500,
        description: "Antalya'nın simgesi olan Yivli Minare Camii, I. Alaaddin Keykubad tarafından yaptırılmıştır. Yivli minaresi 38 metre yüksekliğinde olup, tuğla ve çini ile süslenmiştir.",
        history: "1230 yılında inşa edilmiştir. Minaresi 8 yarım silindirik yivden oluşmaktadır. Turkuaz ve lacivert çinilerle süslüdür.",
        features: ["Yivli (Oluklu) Minare", "38m Yükseklik", "Selçuklu Çinileri", "Antalya'nın Simgesi"]
    },
    {
        id: 56,
        name: "Muratpaşa Camii (Antalya)",
        city: "Antalya",
        district: "Muratpaşa",
        lat: 36.8847,
        lng: 30.7067,
        period: "Osmanlı",
        year: "1570",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Antalya'nın Kaleiçi bölgesinde bulunan Muratpaşa Camii, Osmanlı valisi Murat Paşa tarafından yaptırılmıştır.",
        history: "16. yüzyılda Antalya Valisi Murat Paşa tarafından inşa ettirilmiştir.",
        features: ["Kaleiçi'nde", "Osmanlı Dönemi", "Tarihi Doku", "Murat Paşa Türbesi"]
    },
    {
        id: 57,
        name: "Alaaddin Camii (Antalya)",
        city: "Antalya",
        district: "Muratpaşa",
        lat: 36.8860,
        lng: 30.7090,
        period: "Selçuklu",
        year: "1230",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 1,
        capacity: 800,
        description: "Kaleiçi'ndeki Alaaddin Camii, Anadolu Selçuklu Sultanı I. Alaaddin Keykubad döneminde kiliseden camiye çevrilen bir yapıdır.",
        history: "Selçuklular döneminde kiliseden camiye dönüştürülmüştür. Kaleiçi'nin tarihi cami geleneğinin parçasıdır.",
        features: ["Kiliseden Dönüşüm", "Selçuklu Dönemi", "Kaleiçi"]
    },

    // ==================== DİYARBAKIR ====================
    {
        id: 58,
        name: "Ulu Cami (Diyarbakır)",
        city: "Diyarbakır",
        district: "Sur",
        lat: 37.9100,
        lng: 40.2340,
        period: "Selçuklu",
        year: "1091",
        architect: "Bilinmiyor",
        style: "Büyük Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 5000,
        description: "Anadolu'nun en eski camilerinden biri olan Diyarbakır Ulu Cami, Büyük Selçuklu Sultanı Melikşah döneminde inşa edilmiştir. İslam dünyasının beş önemli camisinden biri olarak kabul edilmektedir.",
        history: "1091 yılında inşa edilmiştir. Emevi Camii planından esinlenilmiştir. Mezopotamya mimarisinin izlerini taşır.",
        features: ["Anadolu'nun En Eski Camilerinden", "Emevi Camii Etkisi", "Bazilika Plan", "İslam'ın 5 Önemli Camisi"]
    },
    {
        id: 59,
        name: "Safa (İparlı Pari) Camii",
        city: "Diyarbakır",
        district: "Sur",
        lat: 37.9082,
        lng: 40.2290,
        period: "Osmanlı",
        year: "1532",
        architect: "Bilinmiyor",
        style: "Osmanlı / Akkoyunlu",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Diyarbakır surlarının içinde yer alan Safa Camii, Akkoyunlu ve Osmanlı dönemlerinin mimari özelliklerini bir arada taşımaktadır.",
        history: "Akkoyunlu Uzun Hasan'ın kızı tarafından yaptırıldığı rivayet edilmektedir. Osmanlı döneminde onarılmıştır.",
        features: ["Sur İçi", "Akkoyunlu Dönemi", "Siyah-Beyaz Taş İşçiliği"]
    },
    {
        id: 60,
        name: "Hz. Süleyman Camii",
        city: "Diyarbakır",
        district: "Sur",
        lat: 37.9140,
        lng: 40.2380,
        period: "Osmanlı",
        year: "1155 (Eyyubi)",
        architect: "Bilinmiyor",
        style: "Eyyubi / Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 800,
        description: "Diyarbakır'ın en kutsal mekanlarından biri olan Hz. Süleyman Camii, sahabeden 27 kişinin gömülü olduğu rivayet edilen bir alanda yer almaktadır.",
        history: "Ashab-ı Kiram'dan 27 kişinin burada medfun olduğuna inanılmaktadır. Diyarbakır'ın en çok ziyaret edilen dini mekanlarından biridir.",
        features: ["Sahabe Makamları", "Kutsal Mekan", "Eyyubi Dönemi"]
    },

    // ==================== SİVAS ====================
    {
        id: 61,
        name: "Divriği Ulu Cami ve Darüşşifası",
        city: "Sivas",
        district: "Divriği",
        lat: 39.3715,
        lng: 38.1189,
        period: "Selçuklu",
        year: "1228-1229",
        architect: "Hürremşah bin Muğis",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "UNESCO Dünya Mirası Listesi'ndeki ilk Türk eseri olan Divriği Ulu Cami ve Darüşşifası, taş işçiliğiyle dünyada eşsiz bir konuma sahiptir.",
        history: "Mengücek Beyliği hükümdarı Ahmed Şah tarafından yaptırılmıştır. 1985 yılında UNESCO Dünya Mirası Listesi'ne alınan ilk Türk eseridir.",
        features: ["UNESCO Dünya Mirası", "Eşsiz Taş İşçiliği", "Darüşşifa (Hastane)", "İlk Türk UNESCO Eseri"]
    },
    {
        id: 62,
        name: "Ulu Cami (Sivas)",
        city: "Sivas",
        district: "Merkez",
        lat: 39.7477,
        lng: 37.0179,
        period: "Selçuklu",
        year: "1197",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Sivas'ın en eski camisi olan Ulu Cami, Anadolu Selçuklu dönemi eserlerindendir.",
        history: "Danişmendliler döneminde inşasına başlanmış, Anadolu Selçukluları döneminde tamamlanmıştır.",
        features: ["Sivas'ın En Eski Camisi", "Selçuklu Minaresi", "Danişmend Dönemi"]
    },
    {
        id: 63,
        name: "Buruciye Medresesi Camii",
        city: "Sivas",
        district: "Merkez",
        lat: 39.7475,
        lng: 37.0170,
        period: "Selçuklu",
        year: "1271",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 2,
        domes: 0,
        capacity: 800,
        description: "Sivas'ın Çifte Minareli yapılarından biri olan Buruciye Medresesi, Selçuklu taş işçiliğinin önemli bir örneğidir. Mescit bölümü cami işlevi görmektedir.",
        history: "Muzaffer Burucirdi tarafından 1271'de yaptırılmıştır. Selçuklu medrese mimarisinin en güzel örneklerinden biridir.",
        features: ["Çifte Minare", "Selçuklu Taş İşçiliği", "Medrese-Cami"]
    },

    // ==================== ERZURUM ====================
    {
        id: 64,
        name: "Çifte Minareli Medrese",
        city: "Erzurum",
        district: "Yakutiye",
        lat: 39.9054,
        lng: 41.2741,
        period: "Selçuklu",
        year: "1271-1272",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 2,
        domes: 0,
        capacity: 1000,
        description: "Erzurum'un simgesi olan Çifte Minareli Medrese, Anadolu Selçuklu mimarisinin en görkemli eserlerinden biridir.",
        history: "İlhanlı Hükümdarı Abaka Han'ın eşi Hüdavend Hatun tarafından yaptırıldığı kabul edilmektedir.",
        features: ["Çifte Minare", "Selçuklu Taş İşçiliği", "Erzurum'un Simgesi", "Görkemli Taç Kapı"]
    },
    {
        id: 65,
        name: "Lala Mustafa Paşa Camii (Erzurum)",
        city: "Erzurum",
        district: "Yakutiye",
        lat: 39.9048,
        lng: 41.2771,
        period: "Osmanlı",
        year: "1562-1563",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Mimar Sinan'ın Erzurum'daki eseri olan Lala Mustafa Paşa Camii, Doğu Anadolu'nun en önemli Osmanlı dönemi camilerinden biridir.",
        history: "Kanuni'nin vezirlerinden Lala Mustafa Paşa tarafından yaptırılmıştır.",
        features: ["Mimar Sinan Eseri", "Doğu Anadolu'nun En Büyük Osmanlı Camisi", "Kalın Duvarlar"]
    },
    {
        id: 66,
        name: "Ulu Cami (Erzurum)",
        city: "Erzurum",
        district: "Yakutiye",
        lat: 39.9060,
        lng: 41.2750,
        period: "Selçuklu",
        year: "1179",
        architect: "Bilinmiyor",
        style: "Saltuklu / Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Erzurum'un en eski camisi olan Ulu Cami, Saltuklular döneminde inşa edilmiştir. Selçuklu mimari geleneğinin Doğu Anadolu'daki önemli bir temsilcisidir.",
        history: "Saltuklu Emiri Nasıreddin Muhammed tarafından 1179'da yaptırılmıştır.",
        features: ["Saltuklu Dönemi", "Erzurum'un En Eski Camisi", "1179"]
    },

    // ==================== ŞANLIURFA ====================
    {
        id: 67,
        name: "Şanlıurfa Ulu Cami",
        city: "Şanlıurfa",
        district: "Haliliye",
        lat: 37.1510,
        lng: 38.7870,
        period: "Osmanlı",
        year: "1170-1175",
        architect: "Bilinmiyor",
        style: "Zengi / Eyyubi",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Haçlılardan geri alınan bir kilisenin camiye dönüştürülmesiyle oluşturulmuştur. Sekizgen çan kulesi minare olarak kullanılmaktadır.",
        history: "Haçlı döneminde kilise olarak kullanılmış, 12. yüzyılda Zengiler tarafından camiye çevrilmiştir.",
        features: ["Kiliseden Dönüşüm", "Sekizgen Minare", "Balıklıgöl Yakınında", "Zengi Dönemi"]
    },
    {
        id: 68,
        name: "Hz. İbrahim (Halilurrahman) Camii",
        city: "Şanlıurfa",
        district: "Haliliye",
        lat: 37.1493,
        lng: 38.7873,
        period: "Osmanlı",
        year: "1211",
        architect: "Bilinmiyor",
        style: "Eyyubi / Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Balıklıgöl'ün hemen yanında yer alan Halilurrahman Camii, Hz. İbrahim'in ateşe atıldığı rivayet edilen yerin üzerine inşa edilmiştir.",
        history: "Eyyubi döneminde inşa edilmiş, Osmanlı döneminde onarılmıştır. Hz. İbrahim'in Nemrut tarafından ateşe atıldığı rivayet edilen kutsal mekan üzerindedir.",
        features: ["Balıklıgöl Yanında", "Hz. İbrahim Makamı", "Kutsal Mekan", "Eyyubi Dönemi"]
    },
    {
        id: 69,
        name: "Rizvaniye Camii (Urfa)",
        city: "Şanlıurfa",
        district: "Haliliye",
        lat: 37.1497,
        lng: 38.7885,
        period: "Osmanlı",
        year: "1716-1736",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Balıklıgöl'ün doğu kıyısında yer alan Rizvaniye Camii, göl manzarasıyla birlikte Şanlıurfa'nın en ikonik görüntülerinden birini oluşturur.",
        history: "Osmanlı valisi Rızvan Ahmet Paşa tarafından 18. yüzyılda yaptırılmıştır.",
        features: ["Balıklıgöl Kıyısı", "İkonik Manzara", "Medrese ile Birlikte"]
    },

    // ==================== HATAY ====================
    {
        id: 70,
        name: "Habib-i Neccar Camii",
        city: "Hatay",
        district: "Antakya",
        lat: 36.2021,
        lng: 36.1607,
        period: "Osmanlı",
        year: "Orijinal: 7. yy",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Anadolu'nun bilinen en eski camisi olan Habib-i Neccar Camii, İslam tarihinde ilk iman eden kişilerden Habib-i Neccar'ın adını taşımaktadır. 2023 depreminde hasar görmüş ve restore edilmiştir.",
        history: "Anadolu'daki ilk cami olduğu kabul edilmektedir. Kur'an-ı Kerim'de Yasin Suresi'nde bahsedilen kişi olarak kabul edilmektedir.",
        features: ["Anadolu'nun En Eski Camisi", "Habib-i Neccar Makamı", "Yasin Suresi", "Deprem Sonrası Restore"]
    },

    // ==================== ADANA ====================
    {
        id: 71,
        name: "Sabancı Merkez Camii",
        city: "Adana",
        district: "Seyhan",
        lat: 36.9920,
        lng: 35.3280,
        period: "Modern",
        year: "1988-1998",
        architect: "Necip Dinç",
        style: "Klasik Osmanlı Esinli",
        minarets: 6,
        domes: 1,
        capacity: 28500,
        description: "Türkiye'nin en büyük camilerinden biri olan Sabancı Merkez Camii, Seyhan Nehri kıyısında yer almaktadır. 6 minaresi ve devasa kubbesiyle Adana'nın simge yapısıdır.",
        history: "Sakıp Sabancı tarafından finanse edilen cami, 10 yıllık inşaat sürecinin ardından 1998'de ibadete açılmıştır.",
        features: ["Türkiye'nin En Büyük Camilerinden", "6 Minare", "28.500 Kişi Kapasitesi", "Seyhan Nehri Kıyısında"]
    },
    {
        id: 72,
        name: "Ulu Cami (Adana)",
        city: "Adana",
        district: "Seyhan",
        lat: 36.9910,
        lng: 35.3253,
        period: "Osmanlı",
        year: "1541",
        architect: "Bilinmiyor",
        style: "Osmanlı / Ramazanoğulları",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Ramazanoğulları Beyliği döneminde inşa edilen Adana Ulu Cami, siyah-beyaz taş işçiliğiyle Memluk etkisini yansıtmaktadır.",
        history: "Ramazanoğulları döneminde yapılmış, Osmanlı döneminde onarılmıştır. Memluk mimarisinin Anadolu'daki yansımalarından biridir.",
        features: ["Ramazanoğulları Dönemi", "Siyah-Beyaz Taş", "Memluk Etkisi"]
    },

    // ==================== KAYSERİ ====================
    {
        id: 73,
        name: "Ulu Cami (Kayseri)",
        city: "Kayseri",
        district: "Melikgazi",
        lat: 38.7330,
        lng: 35.4870,
        period: "Selçuklu",
        year: "1135",
        architect: "Bilinmiyor",
        style: "Danişmendli / Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Kayseri'nin en eski camisi olan Ulu Cami, Danişmendliler döneminde inşa edilmiştir. Anadolu'nun en eski Türk camilerinden biridir.",
        history: "Danişmendli Melik Gazi döneminde 1135'te inşa edilmiştir. Selçuklu ve Osmanlı dönemlerinde çeşitli eklemeler yapılmıştır.",
        features: ["Danişmendli Dönemi", "Kayseri'nin En Eski Camisi", "1135 Yapım Yılı"]
    },
    {
        id: 74,
        name: "Kurşunlu Cami (Kayseri)",
        city: "Kayseri",
        district: "Melikgazi",
        lat: 38.7335,
        lng: 35.4850,
        period: "Osmanlı",
        year: "1585",
        architect: "Mimar Sinan (atfedilen)",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Kurşun kaplı kubbesinden ismini alan Kurşunlu Cami, Mimar Sinan'a atfedilen önemli bir eserdir.",
        history: "Damat İbrahim Paşa tarafından 1585'te yaptırılmıştır.",
        features: ["Kurşun Kubbe", "Mimar Sinan'a Atfedilen", "Kayseri'nin Simge Camisi"]
    },
    {
        id: 75,
        name: "Hunat Hatun Camii (Kayseri)",
        city: "Kayseri",
        district: "Melikgazi",
        lat: 38.7322,
        lng: 35.4880,
        period: "Selçuklu",
        year: "1237-1238",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "Anadolu Selçuklularının önemli kadın banilerinden Hunat (Mahperi) Hatun tarafından yaptırılan cami, medrese, hamam ve türbeden oluşan külliye Kayseri'nin en önemli Selçuklu yapılarındandır.",
        history: "Sultan I. Alaaddin Keykubad'ın eşi Mahperi Hunat Hatun tarafından yaptırılmıştır. Anadolu'da bir kadın tarafından yaptırılan ilk büyük külliyedir.",
        features: ["İlk Kadın Banili Külliye", "Selçuklu Dönemi", "Hamam ve Medrese", "Mahperi Hatun"]
    },

    // ==================== GAZİANTEP ====================
    {
        id: 76,
        name: "Şeyh Fethullah Camii",
        city: "Gaziantep",
        district: "Şahinbey",
        lat: 37.0615,
        lng: 37.3770,
        period: "Osmanlı",
        year: "1563",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Gaziantep'in tarihi merkezinde yer alan Şeyh Fethullah Camii, şehrin en önemli Osmanlı dönemi yapılarından biridir. Kalenin eteklerinde konumlanmıştır.",
        history: "16. yüzyılda inşa edilmiştir. Gaziantep'in dini ve sosyal yaşamında önemli bir yere sahiptir.",
        features: ["Gaziantep Kalesi Yakını", "16. Yüzyıl", "Osmanlı Dönemi"]
    },
    {
        id: 77,
        name: "Boyacı Camii (Gaziantep)",
        city: "Gaziantep",
        district: "Şahinbey",
        lat: 37.0620,
        lng: 37.3790,
        period: "Osmanlı",
        year: "1357",
        architect: "Bilinmiyor",
        style: "Memluk / Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 600,
        description: "Gaziantep'in en eski camilerinden biri olan Boyacı Camii, Memluk mimarisinin izlerini taşımaktadır.",
        history: "14. yüzyılda inşa edilmiştir. Memluk ve Osmanlı dönemlerinin mimari özelliklerini bir arada taşır.",
        features: ["Gaziantep'in En Eski Camisi", "Memluk Etkisi", "14. Yüzyıl"]
    },

    // ==================== MARDİN ====================
    {
        id: 78,
        name: "Ulu Cami (Mardin)",
        city: "Mardin",
        district: "Artuklu",
        lat: 37.3132,
        lng: 40.7294,
        period: "Selçuklu",
        year: "1176",
        architect: "Bilinmiyor",
        style: "Artuklu / Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Mardin'in tarihi silüetinin önemli bir parçası olan Ulu Cami, Artuklu döneminin en güzel eserlerinden biridir. Mezopotamya ovasına bakan konumuyla muhteşem bir manzaraya sahiptir.",
        history: "Artuklu Emiri Kutbeddin İlgazi tarafından 12. yüzyılda yaptırılmıştır.",
        features: ["Artuklu Dönemi", "Mezopotamya Manzarası", "Taş İşçiliği", "Mardin Silüeti"]
    },
    {
        id: 79,
        name: "Kasımiye Medresesi ve Camii",
        city: "Mardin",
        district: "Artuklu",
        lat: 37.3140,
        lng: 40.7310,
        period: "Osmanlı",
        year: "15. yüzyıl",
        architect: "Bilinmiyor",
        style: "Artuklu / Osmanlı",
        minarets: 1,
        domes: 2,
        capacity: 500,
        description: "Mardin'in en görkemli yapılarından biri olan Kasımiye Medresesi, iki kubbeli mescidi ve havuzlu avlusuyla Mezopotamya'ya bakan muhteşem bir konumda yer almaktadır.",
        history: "Artuklu döneminde başlanan yapı, Osmanlı döneminde tamamlanmıştır.",
        features: ["Mezopotamya Manzarası", "İki Kubbeli Mescit", "Havuzlu Avlu", "Artuklu Başyapıtı"]
    },

    // ==================== TRABZON ====================
    {
        id: 80,
        name: "Gülbahar Hatun Camii",
        city: "Trabzon",
        district: "Ortahisar",
        lat: 41.0030,
        lng: 39.7180,
        period: "Osmanlı",
        year: "1514",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Yavuz Sultan Selim'in annesi Gülbahar Hatun adına yaptırılan cami, Trabzon'un en önemli Osmanlı yapılarından biridir.",
        history: "Yavuz Sultan Selim, Trabzon valiliği döneminde annesi Gülbahar Hatun adına bu camiyi yaptırmıştır.",
        features: ["Yavuz Sultan Selim'in Annesi", "Trabzon'un En Büyük Camii", "1514"]
    },
    {
        id: 81,
        name: "Ortahisar Büyük (Fatih) Camii",
        city: "Trabzon",
        district: "Ortahisar",
        lat: 41.0020,
        lng: 39.7210,
        period: "Osmanlı",
        year: "1461 (Dönüşüm)",
        architect: "Bilinmiyor",
        style: "Bizans-Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Aslen bir Bizans kilisesi olan yapı, Fatih Sultan Mehmed'in Trabzon'u fethinden sonra camiye çevrilmiştir. Panagia Chrysokephalos (Altın Başlı Meryem) Kilisesi olarak bilinen yapı, şehrin en eski ibadet mekanlarından biridir.",
        history: "1461 yılında Trabzon'un fethiyle birlikte camiye dönüştürülmüştür.",
        features: ["Bizans Kilisesinden Dönüşüm", "Fatih Dönemi", "Altın Başlı Meryem Kilisesi"]
    },

    // ==================== KASTAMONU ====================
    {
        id: 82,
        name: "Nasrullah Camii (Kastamonu)",
        city: "Kastamonu",
        district: "Merkez",
        lat: 41.3767,
        lng: 33.7764,
        period: "Osmanlı",
        year: "1506",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Kastamonu'nun en büyük ve en önemli camisi olan Nasrullah Camii, ahşap işçiliğiyle ünlüdür.",
        history: "Nasrullah Kadı tarafından 16. yüzyıl başında inşa ettirilmiştir. Ahşap tavan süslemeleri dikkat çekicidir.",
        features: ["Ahşap İşçiliği", "Kastamonu'nun En Büyük Camii", "Osmanlı Taşra Mimarisi"]
    },
    {
        id: 83,
        name: "İbni Neccar Camii (Kastamonu)",
        city: "Kastamonu",
        district: "Merkez",
        lat: 41.3780,
        lng: 33.7750,
        period: "Selçuklu",
        year: "1353",
        architect: "Bilinmiyor",
        style: "Beylikler / Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 600,
        description: "Kastamonu'nun en eski camilerinden olan İbni Neccar Camii, ahşap direkli yapısıyla Anadolu'nun önemli orta çağ camilerindendir.",
        history: "Candaroğulları Beyliği döneminde inşa edilmiştir.",
        features: ["Candaroğulları Dönemi", "Ahşap Direkli", "Kastamonu'nun En Eski Camisi"]
    },

    // ==================== MANİSA ====================
    {
        id: 84,
        name: "Muradiye Camii (Manisa)",
        city: "Manisa",
        district: "Şehzadeler",
        lat: 38.6140,
        lng: 27.4230,
        period: "Osmanlı",
        year: "1583-1586",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 3000,
        description: "Mimar Sinan'ın Manisa'daki eseri olan Muradiye Camii, III. Murad'ın şehzadeliği döneminde yaptırılmıştır. İznik çinileriyle süslü iç mekanı dikkat çekicidir.",
        history: "III. Murad'ın Manisa valiliği döneminde yaptırılmıştır. Mimar Sinan'ın son dönem eserlerindendir.",
        features: ["Mimar Sinan Eseri", "İznik Çinileri", "Şehzade III. Murad Dönemi"]
    },
    {
        id: 85,
        name: "Sultan Camii (Manisa)",
        city: "Manisa",
        district: "Şehzadeler",
        lat: 38.6155,
        lng: 27.4240,
        period: "Osmanlı",
        year: "1522",
        architect: "Acem Ali",
        style: "Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 2500,
        description: "Kanuni Sultan Süleyman'ın annesi Hafsa Sultan tarafından yaptırılan Manisa Sultan Camii, şehrin en büyük Osmanlı külliyesidir.",
        history: "Hafsa Sultan tarafından Kanuni'nin Manisa valiliği döneminde yaptırılmıştır. Külliye bünyesinde medrese, darüşşifa ve hamam bulunmaktadır.",
        features: ["Hafsa Sultan Külliyesi", "Darüşşifa", "Kanuni Dönemi"]
    },

    // ==================== MALATYA ====================
    {
        id: 86,
        name: "Battalgazi Ulu Cami",
        city: "Malatya",
        district: "Battalgazi",
        lat: 38.4289,
        lng: 38.3556,
        period: "Selçuklu",
        year: "1224",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Selçuklu dönemine ait Battalgazi Ulu Cami, spiral tuğla minaresiyle ünlüdür. Selçuklu tuğla mimarisinin önemli bir örneğidir.",
        history: "Anadolu Selçuklu döneminde inşa edilmiştir. Spiral tuğla minaresi Anadolu'da nadir görülen bir uygulamadır.",
        features: ["Spiral Tuğla Minare", "Selçuklu Tuğla Mimarisi", "Eski Malatya"]
    },
    {
        id: 87,
        name: "Yeni Cami (Malatya)",
        city: "Malatya",
        district: "Yeşilyurt",
        lat: 38.3480,
        lng: 38.2950,
        period: "Modern",
        year: "2000",
        architect: "Bilinmiyor",
        style: "Modern Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 10000,
        description: "Malatya'nın yeni şehir merkezindeki en büyük cami. Modern inşaat teknikleriyle klasik Osmanlı mimarisini harmanlayan çağdaş bir yapıdır.",
        history: "2000 yılında ibadete açılmıştır. Malatya'nın en büyük ibadet mekanıdır.",
        features: ["Malatya'nın En Büyük Camii", "Modern Tasarım", "10.000 Kapasitesi"]
    },

    // ==================== AYDIN ====================
    {
        id: 88,
        name: "İlyas Bey Camii (Balat/Milet)",
        city: "Aydın",
        district: "Didim",
        lat: 37.5302,
        lng: 27.2780,
        period: "Selçuklu",
        year: "1404",
        architect: "Bilinmiyor",
        style: "Beylikler Dönemi",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Antik Milet kenti yakınında bulunan İlyas Bey Camii, Menteşeoğulları Beyliği'nden kalan nadide eserlerden biridir. Mermer işçiliğiyle dikkat çeker.",
        history: "Menteşeoğlu İlyas Bey tarafından Timur'un esaretinden dönüşünün şükranesi olarak yaptırılmıştır.",
        features: ["Antik Milet Yakınında", "Menteşeoğulları Dönemi", "Mermer İşçiliği"]
    },

    // ==================== SAKARYA / BİLECİK / ESKİŞEHİR ====================
    {
        id: 89,
        name: "Orhan Camii (Bilecik)",
        city: "Bilecik",
        district: "Söğüt",
        lat: 40.0330,
        lng: 30.1760,
        period: "Osmanlı",
        year: "1324",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Osmanlı Devleti'nin kuruluş yeri Söğüt'teki en eski camilerden biri. Osmanlı mimarisinin ilk örneklerinden biri olarak tarihsel öneme sahiptir.",
        history: "Osmanlı Beyliği'nin ilk döneminde inşa edilmiştir. Söğüt, Osmanlı Devleti'nin doğduğu yerdir.",
        features: ["Osmanlı'nın Kuruluş Yeri", "Erken Osmanlı", "Söğüt"]
    },
    {
        id: 90,
        name: "Alaaddin Camii (Eskişehir)",
        city: "Eskişehir",
        district: "Odunpazarı",
        lat: 39.7689,
        lng: 30.5208,
        period: "Selçuklu",
        year: "13. yüzyıl",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 600,
        description: "Eskişehir'in tarihi Odunpazarı bölgesinde yer alan Alaaddin Camii, Selçuklu dönemine ait en eski yapılardan biridir.",
        history: "Anadolu Selçuklu döneminde inşa edilmiştir. Odunpazarı'nın tarihi dokusunun bir parçasıdır.",
        features: ["Odunpazarı", "Selçuklu Dönemi", "Tarihi Doku"]
    },

    // ==================== TOKAT / AMASYA ====================
    {
        id: 91,
        name: "Gök Medrese Camii (Tokat)",
        city: "Tokat",
        district: "Merkez",
        lat: 40.3110,
        lng: 36.5535,
        period: "Selçuklu",
        year: "1270-1275",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 2,
        domes: 0,
        capacity: 800,
        description: "Tokat'ın simgesi olan Gök Medrese, mavi çini süslemeleriyle ünlüdür. Selçuklu taş ve çini işçiliğinin muhteşem bir örneğidir.",
        history: "Pervane Muineddin Süleyman tarafından 13. yüzyılda yaptırılmıştır.",
        features: ["Mavi Çiniler", "Selçuklu Taş İşçiliği", "Tokat'ın Simgesi"]
    },
    {
        id: 92,
        name: "Bayezid Paşa Camii (Amasya)",
        city: "Amasya",
        district: "Merkez",
        lat: 40.6515,
        lng: 35.8310,
        period: "Osmanlı",
        year: "1414",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Yeşilırmak kıyısında yer alan Bayezid Paşa Camii, Amasya'nın en büyük Osmanlı camisidir. Erken Osmanlı mimarisinin güzel bir örneğidir.",
        history: "I. Mehmed'in veziri Bayezid Paşa tarafından yaptırılmıştır. Yeşilırmak kıyısındaki konumuyla Amasya'nın en güzel yapılarından biridir.",
        features: ["Yeşilırmak Kıyısı", "Erken Osmanlı", "Amasya'nın En Büyük Camisi"]
    },
    {
        id: 93,
        name: "Sultan Bayezid Camii (Amasya)",
        city: "Amasya",
        district: "Merkez",
        lat: 40.6530,
        lng: 35.8330,
        period: "Osmanlı",
        year: "1485-1486",
        architect: "Bilinmiyor",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 2500,
        description: "Sultan II. Bayezid tarafından şehzadeliği döneminde yaptırılan cami, Amasya'nın en görkemli Osmanlı yapısıdır. Külliye bünyesinde medrese, imaret ve hamam da bulunmaktadır.",
        history: "II. Bayezid Amasya valisi iken yaptırmıştır. Şehzade eğitim merkezi olarak da kullanılmıştır.",
        features: ["Şehzade II. Bayezid Dönemi", "Külliye", "Amasya'nın En Görkemli Yapısı"]
    },

    // ==================== AFYONKARAHİSAR ====================
    {
        id: 94,
        name: "Ulu Cami (Afyon)",
        city: "Afyonkarahisar",
        district: "Merkez",
        lat: 38.7370,
        lng: 30.5390,
        period: "Selçuklu",
        year: "1272",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 0,
        domes: 0,
        capacity: 1000,
        description: "Afyon Ulu Cami, 40 ahşap sütunuyla Anadolu'nun en büyük ahşap direkli camilerinden biridir. Selçuklu ahşap işçiliğinin muhteşem bir örneğidir.",
        history: "Sahip Ata döneminde inşa edilmiştir. 40 ahşap sütunu orijinal olarak korunmaktadır.",
        features: ["40 Ahşap Sütun", "Selçuklu Ahşap Geleneği", "Düz Toprak Dam"]
    },

    // ==================== NİĞDE / KARAMAN ====================
    {
        id: 95,
        name: "Alaaddin Camii (Niğde)",
        city: "Niğde",
        district: "Merkez",
        lat: 37.9750,
        lng: 34.6790,
        period: "Selçuklu",
        year: "1223",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Niğde'nin en eski ve en önemli camisi olan Alaaddin Camii, Anadolu Selçuklu döneminin taş işçiliğiyle ünlüdür. Taç kapısı Selçuklu sanatının şaheserlerinden biridir.",
        history: "I. Alaaddin Keykubad döneminde inşa edilmiştir. Taç kapısındaki süslemeler Selçuklu taş işçiliğinin zirvesini temsil eder.",
        features: ["Selçuklu Taç Kapı", "1223", "Niğde'nin En Eski Camisi"]
    },
    {
        id: 96,
        name: "Yunus Emre Camii (Karaman)",
        city: "Karaman",
        district: "Merkez",
        lat: 37.1750,
        lng: 33.2290,
        period: "Osmanlı",
        year: "15. yüzyıl",
        architect: "Bilinmiyor",
        style: "Karamanoğulları",
        minarets: 1,
        domes: 1,
        capacity: 800,
        description: "Yunus Emre'nin türbesinin yanında yer alan cami, Karaman'ın önemli ziyaret mekanlarından biridir. Karamanoğulları Beyliği döneminin mimari özelliklerini taşır.",
        history: "Karamanoğulları döneminde inşa edilmiştir. Yunus Emre'nin türbesiyle birlikte ziyaret edilmektedir.",
        features: ["Yunus Emre Türbesi Yanında", "Karamanoğulları Dönemi", "Ziyaret Mekanı"]
    },

    // ==================== MERSİN ====================
    {
        id: 97,
        name: "Ulu Cami (Tarsus)",
        city: "Mersin",
        district: "Tarsus",
        lat: 36.9160,
        lng: 34.8940,
        period: "Osmanlı",
        year: "1579",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Tarsus'un en büyük ve en önemli camisi olan Ulu Cami, Osmanlı döneminde inşa edilmiştir. Hz. Danyal Makamı'na yakın konumuyla dini turizmin önemli duraklarından biridir.",
        history: "16. yüzyılda Osmanlı döneminde inşa edilmiştir. Tarsus'un tarihi merkezinde yer almaktadır.",
        features: ["Tarsus'un En Büyük Camii", "Hz. Danyal Makamı Yakını", "Osmanlı Dönemi"]
    },
    {
        id: 98,
        name: "Yeni Cami (Mersin)",
        city: "Mersin",
        district: "Akdeniz",
        lat: 36.7990,
        lng: 34.6350,
        period: "Modern",
        year: "1956",
        architect: "Bilinmiyor",
        style: "Cumhuriyet Dönemi",
        minarets: 2,
        domes: 1,
        capacity: 3000,
        description: "Mersin'in en bilinen camilerinden biri olan Yeni Cami, sahil şeridine yakın konumuyla şehrin dini merkezi niteliğindedir.",
        history: "Cumhuriyet döneminde inşa edilmiştir. Mersin'in merkezinde yer almaktadır.",
        features: ["Mersin Merkez", "Sahil Yakını", "Cumhuriyet Dönemi"]
    },

    // ==================== DENİZLİ / MUĞLA ====================
    {
        id: 99,
        name: "Ulu Cami (Denizli)",
        city: "Denizli",
        district: "Merkezefendi",
        lat: 37.7733,
        lng: 29.0878,
        period: "Osmanlı",
        year: "1478",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Denizli'nin merkezinde yer alan Ulu Cami, Osmanlı döneminin şehirdeki en önemli yapılarından biridir.",
        history: "Fatih Sultan Mehmed döneminde inşa edilmiştir. Denizli'nin en eski Osmanlı camisidir.",
        features: ["Fatih Dönemi", "Denizli Merkez", "Osmanlı Dönemi"]
    },
    {
        id: 100,
        name: "Hafsa Sultan Camii (Muğla)",
        city: "Muğla",
        district: "Menteşe",
        lat: 37.2160,
        lng: 28.3640,
        period: "Osmanlı",
        year: "1494",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 800,
        description: "Muğla'nın en önemli tarihî camisi olan Hafsa Sultan Camii, Menteşeoğulları'ndan Osmanlı'ya geçiş döneminin mimari mirasını yansıtmaktadır.",
        history: "15. yüzyıl sonunda inşa edilmiştir. Muğla'nın en eski camisiolarak kabul edilmektedir.",
        features: ["Muğla'nın En Eski Camisi", "15. Yüzyıl", "Osmanlı Dönemi"]
    },

    // ==================== VAN / BİTLİS ====================
    {
        id: 101,
        name: "Ulu Cami (Van)",
        city: "Van",
        district: "İpekyolu",
        lat: 38.4945,
        lng: 43.3800,
        period: "Selçuklu",
        year: "1389",
        architect: "Bilinmiyor",
        style: "Karakoyunlu",
        minarets: 1,
        domes: 0,
        capacity: 1000,
        description: "Van'ın tarihi merkezinde yer alan Ulu Cami, Karakoyunlu dönemine ait önemli bir yapıdır. Van Gölü yakınındaki konumuyla dikkat çeker.",
        history: "Karakoyunlu döneminde inşa edilmiştir. Van'ın en eski Türk-İslam eserlerinden biridir.",
        features: ["Karakoyunlu Dönemi", "Van Gölü Yakını", "Tarihi Merkez"]
    },
    {
        id: 102,
        name: "Ulu Cami (Bitlis)",
        city: "Bitlis",
        district: "Merkez",
        lat: 38.4010,
        lng: 42.1080,
        period: "Selçuklu",
        year: "1150",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1000,
        description: "Bitlis'in en eski ve en büyük camisi olan Ulu Cami, 12. yüzyıla tarihlenen önemli bir Selçuklu eseridir. Taş işçiliğiyle dikkat çeker.",
        history: "12. yüzyılda inşa edilmiştir. Doğu Anadolu'nun en eski camilerinden biridir.",
        features: ["12. Yüzyıl", "Bitlis'in En Eski Camisi", "Selçuklu Taş İşçiliği"]
    },

    // ==================== ÇORUM / SİNOP / SAMSUN ====================
    {
        id: 103,
        name: "Ulu Cami (Çorum)",
        city: "Çorum",
        district: "Merkez",
        lat: 40.5490,
        lng: 34.9540,
        period: "Osmanlı",
        year: "1300'ler",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Çorum'un en önemli tarihi camisi olan Ulu Cami, yüzyıllar boyunca şehrin dini merkezi olmuştur.",
        history: "14. yüzyılda inşa edildiği kabul edilmektedir. Çeşitli dönemlerde onarılmıştır.",
        features: ["Çorum Merkez", "14. Yüzyıl", "Tarihi Doku"]
    },
    {
        id: 104,
        name: "Alaaddin Camii (Sinop)",
        city: "Sinop",
        district: "Merkez",
        lat: 42.0268,
        lng: 35.1520,
        period: "Selçuklu",
        year: "1214",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1000,
        description: "Sinop'un en eski camisi olan Alaaddin Camii, I. İzzeddin Keykavus döneminde Sinop'un fethinden sonra inşa edilmiştir. Karadeniz'in en eski Selçuklu camisidir.",
        history: "Sinop'un 1214'te fethinden hemen sonra inşa edilmiştir. Karadeniz bölgesinin en eski Selçuklu eseridir.",
        features: ["Karadeniz'in En Eski Selçuklu Camisi", "1214", "Sinop Fethi Sonrası"]
    },
    {
        id: 105,
        name: "Büyük Cami (Samsun)",
        city: "Samsun",
        district: "İlkadım",
        lat: 41.2887,
        lng: 36.3340,
        period: "Osmanlı",
        year: "1884",
        architect: "Bilinmiyor",
        style: "Geç Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 3000,
        description: "Samsun'un en büyük tarihi camisi olan Büyük Cami, 19. yüzyıl Osmanlı mimarisinin Karadeniz'deki önemli bir örneğidir.",
        history: "1884 yılında inşa edilmiştir. Samsun'un dini ve sosyal yaşamının merkezidir.",
        features: ["Samsun'un En Büyük Camisi", "19. Yüzyıl", "Geç Osmanlı"]
    },

    // ==================== AKSARAY / NEVŞEHİR ====================
    {
        id: 106,
        name: "Ulu Cami (Aksaray)",
        city: "Aksaray",
        district: "Merkez",
        lat: 38.3723,
        lng: 34.0250,
        period: "Selçuklu",
        year: "1408 (Karamanoğulları)",
        architect: "Bilinmiyor",
        style: "Karamanoğulları",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "Aksaray'ın en önemli tarihi camisi olan Ulu Cami, Karamanoğulları dönemine ait olup kırmızı tuğla minaresiyle dikkat çeker.",
        history: "Karamanoğulları döneminde inşa edilmiştir. Eğri minaresiyle Aksaray'ın simgesi haline gelmiştir.",
        features: ["Eğri Minare", "Karamanoğulları Dönemi", "Kırmızı Tuğla"]
    },

    // ==================== BOLU / DÜZCE / ZONGULDAK ====================
    {
        id: 107,
        name: "Ulu Cami (Bolu)",
        city: "Bolu",
        district: "Merkez",
        lat: 40.7330,
        lng: 31.6100,
        period: "Osmanlı",
        year: "1382",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Bolu'nun en eski ve en önemli camisi olan Ulu Cami, Yıldırım Bayezid döneminde inşa edilmiştir.",
        history: "14. yüzyılda Yıldırım Bayezid döneminde inşa edilmiştir.",
        features: ["Yıldırım Bayezid Dönemi", "Bolu'nun En Eski Camisi", "14. Yüzyıl"]
    },

    // ==================== SAFRANBOLU ====================
    {
        id: 108,
        name: "Köprülü Mehmed Paşa Camii (Safranbolu)",
        city: "Karabük",
        district: "Safranbolu",
        lat: 41.2550,
        lng: 32.6930,
        period: "Osmanlı",
        year: "1661",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "UNESCO Dünya Mirası Listesi'ndeki Safranbolu'nun en önemli camisi. Köprülü Mehmed Paşa tarafından yaptırılan külliyenin parçasıdır.",
        history: "Sadrazam Köprülü Mehmed Paşa tarafından 17. yüzyılda yaptırılmıştır. Safranbolu'nun tarihi dokusunun merkezi yapısıdır.",
        features: ["UNESCO Dünya Mirası Safranbolu", "Köprülü Ailesi", "Külliye"]
    },

    // ==================== ISPARTA / BURDUR ====================
    {
        id: 109,
        name: "Ulu Cami (Isparta)",
        city: "Isparta",
        district: "Merkez",
        lat: 37.7640,
        lng: 30.5530,
        period: "Osmanlı",
        year: "1417",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı / Hamidoğulları",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Isparta'nın en büyük ve en eski camisi olan Ulu Cami, Hamidoğulları Beyliği döneminin mimari özelliklerini taşımaktadır.",
        history: "Hamidoğulları döneminde temeli atılmış, Osmanlı döneminde tamamlanmıştır.",
        features: ["Hamidoğulları Dönemi", "Isparta Merkez", "15. Yüzyıl"]
    },

    // ==================== YOZGAT / KIRŞEHİR ====================
    {
        id: 110,
        name: "Çapanoğlu Camii (Yozgat)",
        city: "Yozgat",
        district: "Merkez",
        lat: 39.7680,
        lng: 34.8140,
        period: "Osmanlı",
        year: "1779",
        architect: "Bilinmiyor",
        style: "Osmanlı Barok",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Yozgat'ın en büyük ve en önemli camisi olan Çapanoğlu Camii, Osmanlı barok mimarisinin Anadolu'daki güzel örneklerinden biridir. İç mekanındaki kalem işleri ve süslemeleriyle dikkat çeker.",
        history: "Yozgat'ın kurucusu Çapanoğlu ailesi tarafından 18. yüzyılda yaptırılmıştır. İç süslemeleri dönemin en zengin örneklerindendir.",
        features: ["Çapanoğlu Ailesi", "Barok Mimari", "Zengin İç Süsleme", "Yozgat'ın Simgesi"]
    },
    {
        id: 111,
        name: "Ahi Evran Camii (Kırşehir)",
        city: "Kırşehir",
        district: "Merkez",
        lat: 39.1420,
        lng: 34.1590,
        period: "Selçuklu",
        year: "1235",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 1,
        capacity: 800,
        description: "Ahi teşkilatının kurucusu Ahi Evran'ın adını taşıyan ve türbesinin yanında yer alan bu cami, Ahilik geleneğinin en önemli merkezi olarak kabul edilmektedir.",
        history: "Ahi Evran, esnaf ve sanatkârlar teşkilatı olan Ahiliğin kurucusudur. Türbesi ve camisi Kırşehir'in en önemli ziyaret mekanıdır.",
        features: ["Ahilik Geleneği", "Ahi Evran Türbesi", "Selçuklu Dönemi"]
    },

    // ==================== ELAZIĞ / TUNCELİ / BİNGÖL ====================
    {
        id: 112,
        name: "Ulu Cami (Harput/Elazığ)",
        city: "Elazığ",
        district: "Merkez (Harput)",
        lat: 38.7100,
        lng: 39.2530,
        period: "Selçuklu",
        year: "1156",
        architect: "Bilinmiyor",
        style: "Artuklu / Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1000,
        description: "Tarihi Harput Kalesi'nin eteklerinde yer alan Ulu Cami, Artuklu dönemine ait Elazığ'ın en eski camisidir. Taş işçiliğiyle dikkat çeker.",
        history: "12. yüzyılda Artuklu döneminde inşa edilmiştir. Harput'un tarihi dokusunun en önemli parçalarından biridir.",
        features: ["Harput Kalesi Etekleri", "Artuklu Dönemi", "12. Yüzyıl"]
    },

    // ==================== KÜTAHYA ====================
    {
        id: 113,
        name: "Ulu Cami (Kütahya)",
        city: "Kütahya",
        district: "Merkez",
        lat: 39.4178,
        lng: 29.9727,
        period: "Osmanlı",
        year: "1410",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı / Germiyanoğulları",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Kütahya'nın en büyük ve en önemli camisi olan Ulu Cami, Germiyanoğulları Beyliği dönemine ait izler taşımaktadır. Kütahya çinileriyle süslü iç mekanı dikkat çekicidir.",
        history: "Germiyanoğulları döneminde temeli atılmış, Osmanlı döneminde genişletilmiştir. Kütahya çini sanatının örnekleri iç mekanda yer almaktadır.",
        features: ["Germiyanoğulları Dönemi", "Kütahya Çinileri", "15. Yüzyıl"]
    },

    // ==================== ÇANAKKALE ====================
    {
        id: 114,
        name: "Yeni Cami (Çanakkale)",
        city: "Çanakkale",
        district: "Merkez",
        lat: 40.1553,
        lng: 26.4130,
        period: "Osmanlı",
        year: "1807",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Çanakkale'nin en büyük tarihi camisi, Boğaz kıyısındaki konumuyla dikkat çeker.",
        history: "19. yüzyıl başında inşa edilmiştir. Çanakkale şehir merkezinin önemli yapılarından biridir.",
        features: ["Boğaz Kıyısı", "Çanakkale Merkez", "19. Yüzyıl"]
    },

    // ==================== BALIKESİR ====================
    {
        id: 115,
        name: "Zağnos Paşa Camii (Balıkesir)",
        city: "Balıkesir",
        district: "Karesi",
        lat: 39.6488,
        lng: 27.8870,
        period: "Osmanlı",
        year: "1461",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Fatih'in komutanlarından Zağnos Paşa tarafından yaptırılan cami, Balıkesir'in en önemli Osmanlı eseridir.",
        history: "İstanbul'un fethinde önemli rol oynayan Zağnos Paşa tarafından 1461'de yaptırılmıştır.",
        features: ["Fatih'in Komutanı", "Zağnos Paşa", "1461"]
    },

    // ==================== TEKİRDAĞ ====================
    {
        id: 116,
        name: "Rüstem Paşa Camii (Tekirdağ)",
        city: "Tekirdağ",
        district: "Süleymanpaşa",
        lat: 40.9800,
        lng: 27.5070,
        period: "Osmanlı",
        year: "1553",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Mimar Sinan'ın Tekirdağ'daki eseri olan Rüstem Paşa Camii, Kanuni'nin damadı Rüstem Paşa adına inşa edilmiştir.",
        history: "Sadrazam Rüstem Paşa tarafından Mimar Sinan'a yaptırılmıştır.",
        features: ["Mimar Sinan Eseri", "Rüstem Paşa", "Tekirdağ Merkez"]
    },

    // ==================== UŞAK ====================
    {
        id: 117,
        name: "Ulu Cami (Uşak)",
        city: "Uşak",
        district: "Merkez",
        lat: 38.6823,
        lng: 29.4058,
        period: "Osmanlı",
        year: "1475",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Uşak'ın en eski ve en büyük camisi olan Ulu Cami, Fatih Sultan Mehmed dönemine ait bir Osmanlı eseridir.",
        history: "15. yüzyılda inşa edilmiştir. Uşak'ın tarihi merkezindeki en önemli yapıdır.",
        features: ["Fatih Dönemi", "Uşak Merkez", "15. Yüzyıl"]
    },

    // ==================== OSMANİYE / K.MARAŞ ====================
    {
        id: 118,
        name: "Ulu Cami (Kahramanmaraş)",
        city: "Kahramanmaraş",
        district: "Onikişubat",
        lat: 37.5850,
        lng: 36.9250,
        period: "Osmanlı",
        year: "1501",
        architect: "Bilinmiyor",
        style: "Dulkadiroğulları / Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Kahramanmaraş'ın en önemli tarihi camisi olan Ulu Cami, Dulkadiroğulları Beyliği döneminin son eserlerinden biridir. Taş işçiliğiyle dikkat çeker.",
        history: "Dulkadiroğlu Alaüddevle Bey döneminde inşa edilmiştir. Osmanlı döneminde onarılmıştır.",
        features: ["Dulkadiroğulları Dönemi", "Taş İşçiliği", "16. Yüzyıl"]
    },

    // ==================== ŞIRNAK / HAKKARİ / AĞRI ====================
    {
        id: 119,
        name: "İshak Paşa Sarayı Camii",
        city: "Ağrı",
        district: "Doğubayazıt",
        lat: 39.7895,
        lng: 44.0165,
        period: "Osmanlı",
        year: "1784",
        architect: "Bilinmiyor",
        style: "Osmanlı / Kafkas / İran",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Doğubayazıt'taki İshak Paşa Sarayı kompleksinin bir parçası olan cami, Osmanlı, İran ve Kafkas mimarisinin eşsiz bir sentezini sunmaktadır. Ağrı Dağı manzarasıyla birlikte muhteşem bir konuma sahiptir.",
        history: "Çıldıroğlu İshak Paşa tarafından 18. yüzyılda yaptırılmıştır. Saray, cami, harem, selamlık ve cephanelikten oluşan büyük bir komplekstir.",
        features: ["İshak Paşa Sarayı", "Ağrı Dağı Manzarası", "Osmanlı-İran-Kafkas Sentezi", "Doğubayazıt"]
    },

    // ==================== MUŞ ====================
    {
        id: 120,
        name: "Alaaddin Paşa Camii (Muş)",
        city: "Muş",
        district: "Merkez",
        lat: 38.7340,
        lng: 41.4930,
        period: "Osmanlı",
        year: "1573",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Muş'un en önemli tarihi camisi olan Alaaddin Paşa Camii, 16. yüzyıl Osmanlı mimarisinin Doğu Anadolu'daki temsilcilerinden biridir.",
        history: "16. yüzyılda inşa edilmiştir. Muş'un en büyük tarihi ibadet mekanıdır.",
        features: ["16. Yüzyıl", "Muş Merkez", "Osmanlı Dönemi"]
    }
];
