const mosqueData = [
    {
        id: 1,
        name: "Sultanahmet Camii (Mavi Cami)",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0054,
        lng: 28.9768,
        period: "Osmanlı",
        year: "1609-1616",
        architect: "Sedefkar Mehmed Ağa",
        style: "Klasik Osmanlı",
        minarets: 6,
        domes: 1,
        capacity: 10000,
        description: "Sultan I. Ahmed tarafından yaptırılan Sultanahmet Camii, altı minaresiyle dünyada benzersiz bir konuma sahiptir. İç mekanındaki mavi İznik çinileri nedeniyle 'Mavi Cami' olarak da bilinir. UNESCO Dünya Mirası Listesi'ndeki İstanbul Tarihi Alanları kapsamında koruma altındadır.",
        history: "Sultan I. Ahmed, henüz 19 yaşındayken bu camiyi yaptırmaya karar vermiştir. Altı minareli olması döneminde tartışmalara yol açmış, Mekke'deki Mescid-i Haram'ın da altı minaresi olduğu için yedinci minare ekletilerek sorun çözülmüştür. Cami, Osmanlı klasik dönem mimarisinin son büyük eseri kabul edilir.",
        features: ["İznik Çinileri", "6 Minare", "UNESCO Dünya Mirası", "260 Pencere"],
        image: ""
    },
    {
        id: 2,
        name: "Ayasofya Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0086,
        lng: 28.9802,
        period: "Osmanlı",
        year: "537 (Cami: 1453)",
        architect: "İsidoros / Anthemios (Orijinal)",
        style: "Bizans-Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 10000,
        description: "Yaklaşık 1500 yıllık tarihiyle dünyanın en önemli mimari yapılarından biri olan Ayasofya, 537'de Bizans İmparatoru Justinianus tarafından kilise olarak inşa edilmiş, 1453'te Fatih Sultan Mehmed tarafından camiye çevrilmiştir. 2020 yılında tekrar ibadete açılmıştır.",
        history: "İlk yapı 360 yılında inşa edilmiş, yangın ve isyanlarla iki kez yıkılmıştır. Bugünkü yapı 532-537 arasında inşa edilmiştir. 916 yıl kilise, 481 yıl cami ve 86 yıl müze olarak hizmet vermiştir. Kubbesi inşa edildiği dönemde mühendislik harikası olarak kabul edilmiştir.",
        features: ["1500 Yıllık Tarih", "Bizans Mozaikleri", "Dev Kubbe (31m)", "UNESCO Dünya Mirası"],
        image: ""
    },
    {
        id: 3,
        name: "Süleymaniye Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0162,
        lng: 28.9640,
        period: "Osmanlı",
        year: "1550-1557",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 5000,
        description: "Mimar Sinan'ın 'kalfalık eserim' dediği Süleymaniye Camii, Kanuni Sultan Süleyman adına inşa edilmiştir. İstanbul'un yedi tepesinden birinin üzerinde yer alan külliye, cami, medrese, hamam, kütüphane ve hastane gibi yapıları barındırır.",
        history: "Kanuni Sultan Süleyman'ın emriyle 1550'de temeli atılmış, 7 yılda tamamlanmıştır. Mimar Sinan bu eseri 'kalfalık eseri' olarak tanımlamıştır. Külliye 22 ayrı yapıdan oluşur ve döneminin en büyük sosyal kompleksiydi.",
        features: ["Mimar Sinan Eseri", "22 Yapılı Külliye", "Akustik Mühendisliği", "Kanuni'nin Türbesi"],
        image: ""
    },
    {
        id: 4,
        name: "Selimiye Camii",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6789,
        lng: 26.5590,
        period: "Osmanlı",
        year: "1568-1574",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 6000,
        description: "Mimar Sinan'ın 'ustalık eserim' dediği Selimiye Camii, Osmanlı mimarisinin en büyük başyapıtlarından biridir. 31.28 metre çapındaki kubbesiyle Ayasofya'yı geçmeyi başarmıştır. 2011 yılında UNESCO Dünya Mirası Listesi'ne alınmıştır.",
        history: "Sultan II. Selim'in emriyle yapılmıştır. Mimar Sinan, 80 yaşını aşkın iken bu camiyi tasarlamış ve 'ustalık eserim' olarak nitelendirmiştir. Ayasofya'nın kubbesini geçme hayalini bu camide gerçekleştirmiştir.",
        features: ["Mimar Sinan'ın Ustalık Eseri", "31.28m Kubbe", "UNESCO Dünya Mirası", "71.5m Minareler"],
        image: ""
    },
    {
        id: 5,
        name: "Kocatepe Camii",
        city: "Ankara",
        district: "Kızılay",
        lat: 39.9199,
        lng: 32.8543,
        period: "Modern",
        year: "1967-1987",
        architect: "Hüsrev Tayla & Fatin Uluengin",
        style: "Neo-Klasik Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 24000,
        description: "Ankara'nın en büyük camii olan Kocatepe Camii, Cumhuriyet döneminin en önemli dini yapılarından biridir. Klasik Osmanlı mimarisi tarzında inşa edilmiş olup, altında bir alışveriş merkezi ve otopark bulunmaktadır.",
        history: "1944 yılında Diyanet İşleri Başkanlığı bünyesinde cami yapım derneği kurularak projeye başlanmıştır. İlk modern tasarım projeleri terk edilerek, klasik Osmanlı üslubunda inşa edilmiştir. 20 yıllık inşaat sürecinin ardından 1987'de ibadete açılmıştır.",
        features: ["Ankara'nın En Büyük Camii", "24.000 Kişi Kapasitesi", "Alışveriş Merkezi Altında", "88m Minareler"],
        image: ""
    },
    {
        id: 6,
        name: "Hacı Bayram Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9413,
        lng: 32.8637,
        period: "Osmanlı",
        year: "1427-1428",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "Ankara'nın en eski ve en kutsal camilerinden biri olan Hacı Bayram Camii, Hacı Bayram-ı Veli tarafından yaptırılmıştır. Augustus Tapınağı'na bitişik konumuyla farklı medeniyetlerin bir arada bulunduğu tarihi bir mekandır.",
        history: "Bayramiye tarikatının kurucusu Hacı Bayram-ı Veli adına 15. yüzyılda inşa edilmiştir. Caminin hemen yanında Roma dönemine ait Augustus Tapınağı yer almaktadır. Çeşitli dönemlerde tamir ve genişletme çalışmaları yapılmıştır.",
        features: ["Augustus Tapınağı Yanında", "Hacı Bayram-ı Veli Türbesi", "Ahşap Tavan", "Çini Süslemeler"],
        image: ""
    },
    {
        id: 7,
        name: "Ulu Cami (Bursa)",
        city: "Bursa",
        district: "Osmangazi",
        lat: 40.1837,
        lng: 29.0597,
        period: "Osmanlı",
        year: "1396-1400",
        architect: "Ali Neccar",
        style: "Erken Osmanlı",
        minarets: 2,
        domes: 20,
        capacity: 5000,
        description: "Bursa Ulu Cami, 20 kubbesiyle Osmanlı mimarisinin en önemli erken dönem eserlerinden biridir. Yıldırım Bayezid tarafından Niğbolu Zaferi'nin ardından yaptırılmıştır. İçindeki hat eserleri ve şadırvan dikkat çekicidir.",
        history: "Yıldırım Bayezid, Niğbolu Savaşı öncesi zafer kazanırsa 20 cami yaptıracağına söz vermiştir. Zaferin ardından 20 ayrı cami yerine 20 kubbeli tek bir cami inşa ettirmiştir. Duvarlarında 192 adet hat levhası bulunmaktadır.",
        features: ["20 Kubbe", "192 Hat Levhası", "İç Şadırvan", "Niğbolu Zaferi Hediyesi"],
        image: ""
    },
    {
        id: 8,
        name: "Yeşil Cami (Bursa)",
        city: "Bursa",
        district: "Yıldırım",
        lat: 40.1787,
        lng: 29.0699,
        period: "Osmanlı",
        year: "1419-1421",
        architect: "Hacı İvaz Paşa",
        style: "Erken Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 2000,
        description: "Sultan I. Mehmed tarafından yaptırılan Yeşil Cami, içindeki yeşil ve mavi tonlarındaki çinileriyle ünlüdür. Osmanlı çini sanatının en güzel örneklerini barındıran cami, Bursa'nın sembol yapılarından biridir.",
        history: "Çelebi Sultan Mehmed tarafından yaptırılmıştır. İsmi içindeki yeşil tonlu çinilerden gelmektedir. Mihrabı Osmanlı çini sanatının başyapıtı kabul edilir. Nakkaş Ali bin İlyas Ali'nin eserleri burada yer alır.",
        features: ["Yeşil Çiniler", "Osmanlı Çini Sanatı", "Sultan Locası", "Yeşil Türbe Yanında"],
        image: ""
    },
    {
        id: 9,
        name: "Sabancı Merkez Camii",
        city: "Adana",
        district: "Seyhan",
        lat: 36.9920,
        lng: 35.3280,
        period: "Modern",
        year: "1988-1998",
        architect: "Necip Dinç",
        style: "Klasik Osmanlı Esinli",
        minarets: 6,
        domes: 1,
        capacity: 28500,
        description: "Türkiye'nin en büyük camilerinden biri olan Sabancı Merkez Camii, Seyhan Nehri kıyısında yer almaktadır. 6 minaresi ve devasa kubbesiyle Adana'nın simge yapısıdır. Sakıp Sabancı tarafından yaptırılmıştır.",
        history: "Sakıp Sabancı tarafından finanse edilen cami, 10 yıllık inşaat sürecinin ardından 1998'de ibadete açılmıştır. Türkiye'nin en büyük camilerinden biri olma özelliğini taşır. Sinan tarzı klasik mimariyi modern inşaat teknikleriyle birleştirmiştir.",
        features: ["Türkiye'nin En Büyük Camilerinden", "6 Minare", "28.500 Kişi Kapasitesi", "Seyhan Nehri Kıyısında"],
        image: ""
    },
    {
        id: 10,
        name: "Çamlıca Camii",
        city: "İstanbul",
        district: "Üsküdar",
        lat: 41.0275,
        lng: 29.0707,
        period: "Modern",
        year: "2013-2019",
        architect: "Bahar Mızrak & Hayriye Gül Totu",
        style: "Modern Osmanlı",
        minarets: 6,
        domes: 1,
        capacity: 63000,
        description: "Türkiye'nin en büyük camii olan Çamlıca Camii, İstanbul'un Anadolu yakasında Çamlıca Tepesi'nde yer almaktadır. 63.000 kişilik kapasitesiyle Türkiye'nin ve Avrupa'nın en büyük camisi unvanını taşımaktadır.",
        history: "2013 yılında temeli atılan cami, 2019'da ibadete açılmıştır. Külliye bünyesinde müze, sanat galerisi, kütüphane ve konferans salonu da bulunmaktadır. 107.1 metre yüksekliğindeki minareleriyle İstanbul siluetinin önemli bir parçası haline gelmiştir.",
        features: ["Türkiye'nin En Büyük Camii", "63.000 Kişi Kapasitesi", "107m Minareler", "Müze ve Sanat Galerisi"],
        image: ""
    },
    {
        id: 11,
        name: "Eyüp Sultan Camii",
        city: "İstanbul",
        district: "Eyüpsultan",
        lat: 41.0484,
        lng: 28.9341,
        period: "Osmanlı",
        year: "1458",
        architect: "Bilinmiyor",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 4000,
        description: "İstanbul'un en kutsal mekanlarından biri olan Eyüp Sultan Camii, Hz. Muhammed'in sancaktarı Ebu Eyyub el-Ensari'nin türbesinin yanında inşa edilmiştir. İstanbul'un fethinden sonra yapılan ilk camilerden biridir.",
        history: "Fatih Sultan Mehmed, İstanbul'un fethinden 5 yıl sonra, Ebu Eyyub el-Ensari'nin mezarının bulunduğu yere camiyi inşa ettirmiştir. Osmanlı padişahlarının kılıç kuşanma törenleri burada yapılırdı. 1798'de III. Selim tarafından yeniden yaptırılmıştır.",
        features: ["İstanbul'un En Kutsal Camisi", "Kılıç Kuşanma Törenleri", "Ebu Eyyub el-Ensari Türbesi", "Fetih Sonrası İlk Cami"],
        image: ""
    },
    {
        id: 12,
        name: "Yeni Cami (Eminönü)",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0053,
        lng: 28.9707,
        period: "Osmanlı",
        year: "1597-1665",
        architect: "Davut Ağa / Dalgıç Ahmed Çavuş",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 5000,
        description: "Eminönü meydanında yer alan Yeni Cami, 66 yıllık inşaat süreciyle dikkat çeker. Safiye Sultan tarafından başlatılan yapı, Turhan Hatice Sultan tarafından tamamlanmıştır. Mısır Çarşısı ile birlikte bir külliye oluşturur.",
        history: "İnşaatına 1597'de başlanmış ancak siyasi istikrarsızlıklar nedeniyle birçok kez durmuştur. Nihayet Turhan Hatice Sultan'ın desteğiyle 1665'te tamamlanmıştır. 66 yıllık inşaat süreci Osmanlı tarihinin en uzun cami inşaatlarından biridir.",
        features: ["66 Yıllık İnşaat", "Mısır Çarşısı Külliyesi", "Eminönü Silüeti", "Valide Sultan Camii"],
        image: ""
    },
    {
        id: 13,
        name: "Mevlana Müzesi ve Camii",
        city: "Konya",
        district: "Karatay",
        lat: 37.8714,
        lng: 32.5044,
        period: "Selçuklu",
        year: "1274",
        architect: "Bedreddin Tebrizli",
        style: "Selçuklu",
        minarets: 0,
        domes: 1,
        capacity: 2000,
        description: "Mevlana Celaleddin-i Rumi'nin türbesinin bulunduğu yapı, yeşil çinili kubbesiyle Konya'nın simgesidir. Mevlevi dergahı olarak da kullanılan yapı, bugün hem müze hem de ibadet mekanı olarak hizmet vermektedir.",
        history: "Mevlana'nın 1273'te vefatının ardından türbesi üzerine inşa edilmiştir. Yeşil kubbe, Karamanoğlu Emir Bedrettin zamanında yaptırılmıştır. Yüzyıllar boyunca Mevlevi tarikatının merkezi olmuştur.",
        features: ["Yeşil Kubbe", "Mevlana Türbesi", "Sema Gösterileri", "Selçuklu Mimarisi"],
        image: ""
    },
    {
        id: 14,
        name: "Alaaddin Camii (Konya)",
        city: "Konya",
        district: "Karatay",
        lat: 37.8739,
        lng: 32.4922,
        period: "Selçuklu",
        year: "1155-1220",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Konya'nın merkezinde, Alaaddin Tepesi üzerinde yer alan bu cami, Anadolu Selçuklu Devleti'nin en önemli dini yapılarından biridir. Birçok Selçuklu sultanının türbesi burada bulunmaktadır.",
        history: "I. Mesud döneminde inşasına başlanmış, I. Alaaddin Keykubad döneminde tamamlanmıştır. Selçuklu sarayının yanında yer alan cami, devletin resmi camisiydi. 8 Selçuklu sultanının türbesi burada bulunmaktadır.",
        features: ["Selçuklu Sarayı Yanında", "8 Sultan Türbesi", "Minber (1155)", "Anadolu'nun En Eski Camilerinden"],
        image: ""
    },
    {
        id: 15,
        name: "Divriği Ulu Cami ve Darüşşifası",
        city: "Sivas",
        district: "Divriği",
        lat: 39.3715,
        lng: 38.1189,
        period: "Selçuklu",
        year: "1228-1229",
        architect: "Hürremşah bin Muğis",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "UNESCO Dünya Mirası Listesi'ndeki ilk Türk eseri olan Divriği Ulu Cami ve Darüşşifası, taş işçiliğiyle dünyada eşsiz bir konuma sahiptir. Üç kapısındaki taş süslemeler, Orta Çağ sanatının en olağanüstü örnekleri arasındadır.",
        history: "Mengücek Beyliği hükümdarı Ahmed Şah tarafından yaptırılmıştır. Darüşşifa kısmı ise eşi Turan Melek Sultan tarafından inşa ettirilmiştir. 1985 yılında UNESCO Dünya Mirası Listesi'ne alınan ilk Türk eseridir.",
        features: ["UNESCO Dünya Mirası", "Eşsiz Taş İşçiliği", "Darüşşifa (Hastane)", "İlk Türk UNESCO Eseri"],
        image: ""
    },
    {
        id: 16,
        name: "Şehzade Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0118,
        lng: 28.9563,
        period: "Osmanlı",
        year: "1543-1548",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 3000,
        description: "Mimar Sinan'ın 'çıraklık eserim' dediği Şehzade Camii, Kanuni Sultan Süleyman'ın genç yaşta ölen oğlu Şehzade Mehmed için yaptırılmıştır. Sinan'ın ilk büyük eseri olarak Osmanlı mimarisinde önemli bir yere sahiptir.",
        history: "Kanuni Sultan Süleyman, 22 yaşında ölen oğlu Şehzade Mehmed'in anısına bu camiyi yaptırmıştır. Mimar Sinan bu eseri çıraklık dönemi yapıtı olarak tanımlar. Külliye bünyesinde medrese, imaret ve türbeler bulunmaktadır.",
        features: ["Mimar Sinan'ın Çıraklık Eseri", "Şehzade Mehmed Anısına", "Simetrik Tasarım", "Renkli Taş Süslemeler"],
        image: ""
    },
    {
        id: 17,
        name: "Rüstem Paşa Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0164,
        lng: 28.9690,
        period: "Osmanlı",
        year: "1561-1563",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Eminönü'nde yer alan Rüstem Paşa Camii, İznik çinilerinin en yoğun kullanıldığı Osmanlı camilerinden biridir. Kanuni'nin damadı Rüstem Paşa adına Mimar Sinan tarafından inşa edilmiştir.",
        history: "Kanuni Sultan Süleyman'ın damadı ve Sadrazamı Rüstem Paşa için yapılmıştır. Caminin iç duvarları tamamen İznik çinileriyle kaplıdır. Çini süslemelerin zenginliği ve çeşitliliğiyle Osmanlı sanatının şaheserlerinden biridir.",
        features: ["İznik Çinileri", "Mimar Sinan Eseri", "Yükseltilmiş Platform", "Lale Motifleri"],
        image: ""
    },
    {
        id: 18,
        name: "İsa Bey Camii",
        city: "İzmir",
        district: "Selçuk",
        lat: 37.9425,
        lng: 27.3697,
        period: "Selçuklu",
        year: "1374-1375",
        architect: "Şamlı Ali bin Dımışki",
        style: "Aydınoğulları / Selçuklu",
        minarets: 2,
        domes: 2,
        capacity: 2000,
        description: "Efes antik kenti yakınında yer alan İsa Bey Camii, Aydınoğulları Beyliği dönemine ait önemli bir eserdir. Selçuklu ve Beylikler dönemi mimarisinin en güzel örneklerinden biri olup, Artemis Tapınağı'nın sütunları kullanılarak inşa edilmiştir.",
        history: "Aydınoğlu İsa Bey tarafından 1375'te yaptırılmıştır. Efes'teki Artemis Tapınağı'ndan devşirme malzemeler kullanılmıştır. Avlu düzenlemesi ve taç kapısı ile Anadolu Türk mimarisinde özel bir yere sahiptir.",
        features: ["Efes Yakınında", "Artemis Tapınağı Sütunları", "Beylikler Dönemi", "Avlulu Cami Planı"],
        image: ""
    },
    {
        id: 19,
        name: "Hisar Camii",
        city: "İzmir",
        district: "Konak",
        lat: 38.4199,
        lng: 27.1289,
        period: "Osmanlı",
        year: "1597",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "İzmir'in en büyük ve en eski Osmanlı camisi olan Hisar Camii, Kemeralti çarşısı içinde yer almaktadır. Osmanlı barok üslubundaki süslemeleri ve geniş iç mekanıyla dikkat çeker.",
        history: "16. yüzyıl sonlarında inşa edilmiş, sonraki yüzyıllarda çeşitli onarımlardan geçmiştir. İzmir'in en önemli Osmanlı dönemi eseri olarak kabul edilmektedir. Cuma namazlarında büyük cemaatlere ev sahipliği yapmaktadır.",
        features: ["İzmir'in En Büyük Camii", "Kemeralti Çarşısı İçinde", "Barok Süslemeler", "Tarihi Vaaz Kürsüsü"],
        image: ""
    },
    {
        id: 20,
        name: "Yivli Minare Camii",
        city: "Antalya",
        district: "Muratpaşa",
        lat: 36.8856,
        lng: 30.7068,
        period: "Selçuklu",
        year: "1230",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 6,
        capacity: 1500,
        description: "Antalya'nın simgesi olan Yivli Minare Camii, Anadolu Selçuklu Sultanı I. Alaaddin Keykubad tarafından yaptırılmıştır. Yivli (oluklu) minaresi 38 metre yüksekliğinde olup, tuğla ve çini ile süslenmiştir.",
        history: "1230 yılında I. Alaaddin Keykubad döneminde inşa edilmiştir. Minaresi 8 yarım silindirik yivden oluşmaktadır. Minarenin gövdesi turkuaz ve lacivert çinilerle süslüdür. Antalya'nın en tanınmış simgesidir.",
        features: ["Yivli (Oluklu) Minare", "38m Yükseklik", "Selçuklu Çinileri", "Antalya'nın Simgesi"],
        image: ""
    },
    {
        id: 21,
        name: "Muratpaşa Camii",
        city: "Antalya",
        district: "Muratpaşa",
        lat: 36.8847,
        lng: 30.7067,
        period: "Osmanlı",
        year: "1570",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Antalya'nın Kaleiçi bölgesinde bulunan Muratpaşa Camii, Osmanlı valisi Murat Paşa tarafından yaptırılmıştır. Tarihi dokusu ve konumuyla öne çıkan cami, Kaleiçi'nin önemli yapılarından biridir.",
        history: "16. yüzyılda Antalya Valisi Murat Paşa tarafından inşa ettirilmiştir. Kaleiçi'nin tarihi dokusuna uygun olarak restore edilmiştir.",
        features: ["Kaleiçi'nde", "Osmanlı Dönemi", "Tarihi Doku", "Murat Paşa Türbesi"],
        image: ""
    },
    {
        id: 22,
        name: "Ulu Cami (Diyarbakır)",
        city: "Diyarbakır",
        district: "Sur",
        lat: 37.9100,
        lng: 40.2340,
        period: "Selçuklu",
        year: "1091",
        architect: "Bilinmiyor",
        style: "Büyük Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 5000,
        description: "Anadolu'nun en eski camilerinden biri olan Diyarbakır Ulu Cami, Büyük Selçuklu Sultanı Melikşah döneminde inşa edilmiştir. Şam Emevi Camii'nden esinlenerek yapılmış olup, Anadolu'daki ilk büyük cami olma özelliğini taşır.",
        history: "1091 yılında Büyük Selçuklu döneminde inşa edilmiştir. Emevi Camii planından esinlenilmiştir. İslam dünyasının beş önemli camisinden biri olarak kabul edilmektedir. Mezopotamya mimarisinin izlerini taşır.",
        features: ["Anadolu'nun En Eski Camilerinden", "Emevi Camii Etkisi", "Bazilika Plan", "İslam'ın 5 Önemli Camisi"],
        image: ""
    },
    {
        id: 23,
        name: "Ortaköy Camii (Büyük Mecidiye)",
        city: "İstanbul",
        district: "Beşiktaş",
        lat: 41.0472,
        lng: 29.0275,
        period: "Osmanlı",
        year: "1854-1856",
        architect: "Nigoğayos Balyan",
        style: "Neo-Barok",
        minarets: 2,
        domes: 1,
        capacity: 1500,
        description: "Boğaz kıyısında yer alan Ortaköy Camii, İstanbul'un en fotoğraflanan yapılarından biridir. Sultan Abdülmecid tarafından yaptırılan cami, neo-barok mimarisiyle farklı bir üslup sergiler. Boğaziçi Köprüsü'yle manzarası ikonik hale gelmiştir.",
        history: "Sultan Abdülmecid tarafından eski bir caminin yerine yaptırılmıştır. Mimar Nigoğayos Balyan'ın eseridir. Geniş pencereleri Boğaz'ın ışığını içeriye taşır. 'Su üstünde yüzen cami' olarak da anılır.",
        features: ["Boğaz Manzarası", "Neo-Barok Üslup", "Fotoğrafçıların Gözdesi", "Boğaziçi Köprüsü İle İkonik Manzara"],
        image: ""
    },
    {
        id: 24,
        name: "Eski Cami (Edirne)",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6770,
        lng: 26.5560,
        period: "Osmanlı",
        year: "1403-1414",
        architect: "Konyalı Hacı Alaaddin / Ömer bin İbrahim",
        style: "Erken Osmanlı",
        minarets: 2,
        domes: 9,
        capacity: 3000,
        description: "Edirne'nin en eski camisi olan Eski Cami, Emir Süleyman Çelebi tarafından başlatılıp I. Mehmed döneminde tamamlanmıştır. 9 kubbeli yapısı ve devasa hat yazılarıyla dikkat çeker. Bursa Ulu Cami'nin bir devamı niteliğindedir.",
        history: "Fetret Devri'nde başlanan yapı, I. Mehmed (Çelebi Mehmed) döneminde tamamlanmıştır. Osmanlı hat sanatının en büyük örneklerinden biri olarak kabul edilir. Duvarlarındaki dev hat yazıları çok etkileyicidir.",
        features: ["9 Kubbe", "Dev Hat Yazıları", "Edirne'nin En Eski Camisi", "Fetret Devri Eseri"],
        image: ""
    },
    {
        id: 25,
        name: "Üç Şerefeli Cami",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6785,
        lng: 26.5557,
        period: "Osmanlı",
        year: "1437-1447",
        architect: "Bilinmiyor",
        style: "Geçiş Dönemi Osmanlı",
        minarets: 4,
        domes: 1,
        capacity: 3000,
        description: "Osmanlı mimarisinde tek kubbeli cami geleneğini başlatan Üç Şerefeli Cami, II. Murad tarafından yaptırılmıştır. Bir minaresinde üç şerefe bulunması nedeniyle bu ismi almıştır. Dört minaresi birbirinden farklı tasarımdadır.",
        history: "II. Murad'ın emriyle 10 yılda inşa edilmiştir. Osmanlı mimarisinde çok kubbeli yapıdan tek kubbeye geçişin ilk örneğidir. Her minaresinin farklı üslupta olması dikkat çekicidir.",
        features: ["3 Şerefeli Minare", "Tek Kubbe Geleneğinin Başlangıcı", "4 Farklı Minare", "Geçiş Dönemi Eseri"],
        image: ""
    },
    {
        id: 26,
        name: "Makbul İbrahim Paşa Camii (Şehzadebaşı)",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0135,
        lng: 28.9508,
        period: "Osmanlı",
        year: "1551",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 800,
        description: "Mimar Sinan'ın küçük ama zarif eserlerinden biri olan bu cami, Kanuni döneminin önemli yapılarından biridir.",
        history: "Kanuni Sultan Süleyman dönemi sadrazamlarından İbrahim Paşa adına inşa edilmiştir.",
        features: ["Mimar Sinan Eseri", "Zarif Tasarım", "Kanuni Dönemi"],
        image: ""
    },
    {
        id: 27,
        name: "Mihrimah Sultan Camii (Edirnekapı)",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0283,
        lng: 28.9393,
        period: "Osmanlı",
        year: "1562-1565",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Mimar Sinan'ın Kanuni'nin kızı Mihrimah Sultan için yaptığı iki camiden biri olan Edirnekapı Mihrimah Sultan Camii, İstanbul'un en yüksek noktasında yer alır. Işık dolu iç mekanıyla 'ışık camisi' olarak da bilinir.",
        history: "Kanuni Sultan Süleyman'ın kızı Mihrimah Sultan için yapılmıştır. 161 penceresiyle aydınlık bir iç mekana sahiptir. Mimar Sinan'ın Mihrimah Sultan'a duyduğu platonik aşkın simgesi olarak da anlatılır.",
        features: ["161 Pencere", "Işık Camisi", "İstanbul'un En Yüksek Noktası", "Mimar Sinan'ın Aşk Eseri"],
        image: ""
    },
    {
        id: 28,
        name: "Nasrullah Camii",
        city: "Kastamonu",
        district: "Merkez",
        lat: 41.3767,
        lng: 33.7764,
        period: "Osmanlı",
        year: "1506",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Kastamonu'nun en büyük ve en önemli camisi olan Nasrullah Camii, ahşap işçiliğiyle ünlüdür. Osmanlı taşra mimarisinin önemli örneklerinden biridir.",
        history: "Nasrullah Kadı tarafından 16. yüzyıl başında inşa ettirilmiştir. Ahşap tavan süslemeleri ve mihrabı özellikle dikkat çekicidir.",
        features: ["Ahşap İşçiliği", "Kastamonu'nun En Büyük Camii", "Osmanlı Taşra Mimarisi"],
        image: ""
    },
    {
        id: 29,
        name: "Ulu Cami (Malatya - Battalgazi)",
        city: "Malatya",
        district: "Battalgazi",
        lat: 38.4289,
        lng: 38.3556,
        period: "Selçuklu",
        year: "1224",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1000,
        description: "Anadolu Selçuklu dönemine ait olan Battalgazi Ulu Cami, tuğla ve taş işçiliğiyle Selçuklu mimarisinin güzel örneklerinden biridir. Geometrik desenleri ve çini süslemeleriyle dikkat çeker.",
        history: "1224 yılında Anadolu Selçuklu döneminde inşa edilmiştir. Battalgazi, Malatya'nın eski yerleşim merkezidir. Geometrik tuğla örgüleri Selçuklu sanatının karakteristik özelliklerini taşır.",
        features: ["Selçuklu Tuğla İşçiliği", "Geometrik Desenler", "Battalgazi Tarihi Doku"],
        image: ""
    },
    {
        id: 30,
        name: "Cenabi Ahmet Paşa Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9350,
        lng: 32.8550,
        period: "Osmanlı",
        year: "1565-1566",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Mimar Sinan'ın Ankara'daki tek eseri olan Cenabi Ahmet Paşa Camii, klasik Osmanlı mimarisinin başkentteki en güzel örneklerinden biridir. Altıgen planlı yapısıyla dikkat çeker.",
        history: "Beylerbeyisi Cenabi Ahmet Paşa tarafından Mimar Sinan'a yaptırılmıştır. Ankara'daki tek Mimar Sinan eseridir. Altıgen plan şeması Osmanlı mimarisinde nadir görülen bir uygulamadır.",
        features: ["Mimar Sinan Eseri", "Altıgen Plan", "Ankara'daki Tek Sinan Eseri"],
        image: ""
    },
    {
        id: 31,
        name: "Kurşunlu Camii",
        city: "Kayseri",
        district: "Melikgazi",
        lat: 38.7330,
        lng: 35.4850,
        period: "Osmanlı",
        year: "1585",
        architect: "Mimar Sinan (atfedilen)",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Kayseri'nin en önemli Osmanlı camilerinden biri olan Kurşunlu Cami, kurşun kaplı kubbesinden ismini almıştır. Mimar Sinan'a atfedilen yapı, klasik Osmanlı üslubunun Anadolu'daki güzel bir temsilcisidir.",
        history: "Damat İbrahim Paşa tarafından 1585'te yaptırılmıştır. Kubbesinin kurşun kaplaması nedeniyle bu ismi almıştır. Kayseri'nin en büyük Osmanlı dönemi camilerindendir.",
        features: ["Kurşun Kubbe", "Mimar Sinan'a Atfedilen", "Kayseri'nin Simge Camisi"],
        image: ""
    },
    {
        id: 32,
        name: "Ulu Cami (Sivas)",
        city: "Sivas",
        district: "Merkez",
        lat: 39.7477,
        lng: 37.0179,
        period: "Selçuklu",
        year: "1197",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Sivas'ın en eski camisi olan Ulu Cami, Anadolu Selçuklu dönemi eserlerindendir. Tuğladan yapılmış minaresiyle dikkat çeken yapı, yüzyıllar boyunca çeşitli restorasyon ve eklemelerle bugünkü halini almıştır.",
        history: "Danişmendliler döneminde inşasına başlanmış, Anadolu Selçukluları döneminde tamamlanmıştır. Sivas'ın en eski ibadet mekanıdır.",
        features: ["Sivas'ın En Eski Camisi", "Selçuklu Minaresi", "Danişmend Dönemi"],
        image: ""
    },
    {
        id: 33,
        name: "Manisa Ulu Cami",
        city: "Manisa",
        district: "Şehzadeler",
        lat: 38.6128,
        lng: 27.4260,
        period: "Osmanlı",
        year: "1366-1376",
        architect: "Bilinmiyor",
        style: "Beylikler / Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Saruhanoğulları Beyliği döneminde inşa edilen Manisa Ulu Cami, Batı Anadolu'nun en önemli Beylikler dönemi yapılarından biridir. Taş ve tuğla işçiliğiyle dikkat çeker.",
        history: "Saruhanoğlu İshak Bey tarafından yaptırılmıştır. Beylikler dönemi mimarisinin Batı Anadolu'daki en önemli örneklerinden biridir.",
        features: ["Saruhanoğulları Dönemi", "Beylikler Mimarisi", "Taş-Tuğla İşçiliği"],
        image: ""
    },
    {
        id: 34,
        name: "Muradiye Camii (Edirne)",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6815,
        lng: 26.5620,
        period: "Osmanlı",
        year: "1435",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "II. Murad tarafından yaptırılan Muradiye Camii, özellikle çini süslemeleriyle ünlüdür. Edirne'nin en güzel çinili camilerinden biri olarak kabul edilmektedir.",
        history: "II. Murad döneminde Mevlevi dergahı olarak da kullanılmak üzere inşa edilmiştir. İç mekanındaki çiniler döneminin en güzel örnekleridir.",
        features: ["Çini Süslemeler", "Mevlevi Dergahı", "II. Murad Dönemi"],
        image: ""
    },
    {
        id: 35,
        name: "Aziziye Camii",
        city: "Konya",
        district: "Karatay",
        lat: 37.8699,
        lng: 32.4977,
        period: "Osmanlı",
        year: "1874",
        architect: "Bilinmiyor",
        style: "Barok-Rokoko",
        minarets: 2,
        domes: 1,
        capacity: 1500,
        description: "Konya'nın merkezinde yer alan Aziziye Camii, Osmanlı barok ve rokoko stilinin Anadolu'daki nadir örneklerinden biridir. Çifte minareleri farklı üslupta tasarlanmış olup dikkat çekicidir.",
        history: "Sultan Abdülaziz döneminde inşa edilmiştir. İki kez yanan cami, üçüncü kez bugünkü haliyle yeniden yapılmıştır. Gotik ve barok öğelerin harmanlandığı eşsiz bir mimari tarz sergiler.",
        features: ["Barok-Rokoko Üslup", "Gotik Öğeler", "Çifte Minare", "Üç Kez İnşa Edilmiş"],
        image: ""
    },
    {
        id: 36,
        name: "Akşehir Ulu Cami",
        city: "Konya",
        district: "Akşehir",
        lat: 38.3560,
        lng: 31.4160,
        period: "Selçuklu",
        year: "1213",
        architect: "Bilinmiyor",
        style: "Anadolu Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1000,
        description: "Nasreddin Hoca'nın memleketi Akşehir'deki Ulu Cami, Selçuklu ahşap direkli cami geleneğinin güzel bir örneğidir. Ahşap sütunları ve orijinal mihrabıyla tarihi değer taşır.",
        history: "Sahip Ata Fahrettin Ali tarafından inşa ettirilmiştir. Selçuklu ahşap direkli cami tipinin Anadolu'daki en güzel örneklerinden biridir.",
        features: ["Ahşap Direkli Cami", "Selçuklu Dönemi", "Nasreddin Hoca Memleketi"],
        image: ""
    },
    {
        id: 37,
        name: "Beyazıt Camii (İstanbul)",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0105,
        lng: 28.9646,
        period: "Osmanlı",
        year: "1500-1506",
        architect: "Yakub Şah bin Sultan Şah",
        style: "Erken Klasik Osmanlı",
        minarets: 2,
        domes: 1,
        capacity: 4000,
        description: "İstanbul'daki en eski ayakta kalan padişah camisi olan Beyazıt Camii, II. Bayezid tarafından yaptırılmıştır. Osmanlı mimarisinde erken klasik dönemin önemli bir eseridir.",
        history: "Sultan II. Bayezid'in emriyle 1500-1506 yılları arasında inşa edilmiştir. İstanbul'da ayakta kalan en eski sultan camisidir. Osmanlı klasik mimarisinin temellerini atmıştır.",
        features: ["İstanbul'un En Eski Sultan Camisi", "Erken Klasik Dönem", "Beyazıt Meydanı"],
        image: ""
    },
    {
        id: 38,
        name: "Fatih Camii",
        city: "İstanbul",
        district: "Fatih",
        lat: 41.0198,
        lng: 28.9499,
        period: "Osmanlı",
        year: "1463-1470 (Yeniden: 1767-1771)",
        architect: "Atik Sinan (Orijinal) / Mehmed Tahir Ağa (Yeniden)",
        style: "Klasik Osmanlı / Barok",
        minarets: 2,
        domes: 1,
        capacity: 10000,
        description: "Fatih Sultan Mehmed tarafından İstanbul'un fethinden sonra yaptırılan ilk büyük külliye olan Fatih Camii, 1766 depreminde yıkılmış ve III. Mustafa döneminde yeniden inşa edilmiştir. Fatih'in türbesi avluda yer almaktadır.",
        history: "İstanbul'un fethinden sonra inşa edilen ilk büyük padişah külliyesidir. Orijinal yapı 1766 depreminde ağır hasar görmüş, barok üslupta yeniden inşa edilmiştir. Fatih Sultan Mehmed'in türbesi burada bulunmaktadır.",
        features: ["Fatih Sultan Mehmed Türbesi", "İstanbul'un İlk Büyük Külliyesi", "Deprem Sonrası Yeniden İnşa", "8 Medrese"],
        image: ""
    },
    {
        id: 39,
        name: "Hüdavendigar Camii",
        city: "Bursa",
        district: "Osmangazi",
        lat: 40.1930,
        lng: 29.0175,
        period: "Osmanlı",
        year: "1365-1385",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Sultan I. Murad (Hüdavendigar) tarafından yaptırılan bu yapı, alt katı cami, üst katı medrese olan dünyada eşsiz bir tasarıma sahiptir. Çekirge semtinde termal bölgede yer alır.",
        history: "I. Murad döneminde inşa edilmiştir. Alt katı cami, üst katı medrese olan iki katlı yapısıyla dünyada tek örnektir. Ters T planlı ilk Osmanlı camilerinden biridir.",
        features: ["İki Katlı Cami-Medrese", "Dünyada Tek Örnek", "Ters T Plan", "Çekirge Semtinde"],
        image: ""
    },
    {
        id: 40,
        name: "İlyas Bey Camii",
        city: "Aydın",
        district: "Didim (Balat/Milet)",
        lat: 37.5302,
        lng: 27.2780,
        period: "Selçuklu",
        year: "1404",
        architect: "Bilinmiyor",
        style: "Beylikler Dönemi",
        minarets: 1,
        domes: 1,
        capacity: 500,
        description: "Antik Milet kenti yakınında bulunan İlyas Bey Camii, Menteşeoğulları Beyliği'nden kalan nadide eserlerden biridir. Mermer işçiliğiyle Beylikler dönemi mimarisinin en güzel örneklerinden biridir.",
        history: "Menteşeoğlu İlyas Bey tarafından Timur'un esaretinden dönüşünün şükranesi olarak yaptırılmıştır. Antik Milet'in kalıntıları üzerine inşa edilmiştir.",
        features: ["Antik Milet Yakınında", "Menteşeoğulları Dönemi", "Mermer İşçiliği", "Devşirme Malzeme"],
        image: ""
    },
    {
        id: 41,
        name: "Çifte Minareli Medrese",
        city: "Erzurum",
        district: "Yakutiye",
        lat: 39.9054,
        lng: 41.2741,
        period: "Selçuklu",
        year: "1271-1272",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 2,
        domes: 0,
        capacity: 1000,
        description: "Erzurum'un simgesi olan Çifte Minareli Medrese, Anadolu Selçuklu mimarisinin en görkemli eserlerinden biridir. Taç kapısı ve çifte minareleriyle Selçuklu taş işçiliğinin zirvesini temsil eder.",
        history: "İlhanlı Hükümdarı Abaka Han'ın eşi Hüdavend Hatun tarafından yaptırıldığı kabul edilmektedir. Selçuklu taş süsleme sanatının en görkemli örneklerinden biridir.",
        features: ["Çifte Minare", "Selçuklu Taş İşçiliği", "Erzurum'un Simgesi", "Görkemli Taç Kapı"],
        image: ""
    },
    {
        id: 42,
        name: "Lala Mustafa Paşa Camii",
        city: "Erzurum",
        district: "Yakutiye",
        lat: 39.9048,
        lng: 41.2771,
        period: "Osmanlı",
        year: "1562-1563",
        architect: "Mimar Sinan",
        style: "Klasik Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 2000,
        description: "Mimar Sinan'ın Erzurum'daki eseri olan Lala Mustafa Paşa Camii, Doğu Anadolu'nun en önemli Osmanlı dönemi camilerinden biridir. Soğuk iklime uygun kalın duvarlarıyla dikkat çeker.",
        history: "Kanuni Sultan Süleyman'ın vezirlerinden Lala Mustafa Paşa tarafından yaptırılmıştır. Mimar Sinan'ın Doğu Anadolu'daki ender eserlerinden biridir.",
        features: ["Mimar Sinan Eseri", "Doğu Anadolu'nun En Büyük Osmanlı Camisi", "Kalın Duvarlar"],
        image: ""
    },
    {
        id: 43,
        name: "Şanlıurfa Ulu Cami",
        city: "Şanlıurfa",
        district: "Haliliye",
        lat: 37.1510,
        lng: 38.7870,
        period: "Osmanlı",
        year: "1170-1175",
        architect: "Bilinmiyor",
        style: "Zengi / Eyyubi",
        minarets: 1,
        domes: 0,
        capacity: 2000,
        description: "Şanlıurfa Ulu Cami, Haçlılardan geri alınan bir kilisenin camiye dönüştürülmesiyle oluşturulmuştur. Sekizgen çan kulesi minare olarak kullanılmaktadır. Balıklıgöl ile birlikte Urfa'nın en önemli dini mekanlarından biridir.",
        history: "Haçlı döneminde kilise olarak kullanılmış, 12. yüzyılda Zengiler tarafından camiye çevrilmiştir. Kilisenin çan kulesi minare olarak kullanılmaya devam etmektedir.",
        features: ["Kiliseden Dönüşüm", "Sekizgen Minare", "Balıklıgöl Yakınında", "Zengi Dönemi"],
        image: ""
    },
    {
        id: 44,
        name: "Hz. İbrahim (Halilurrahman) Camii",
        city: "Şanlıurfa",
        district: "Haliliye",
        lat: 37.1493,
        lng: 38.7873,
        period: "Osmanlı",
        year: "1211",
        architect: "Bilinmiyor",
        style: "Eyyubi / Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Balıklıgöl'ün hemen yanında yer alan Halilurrahman Camii, Hz. İbrahim'in ateşe atıldığı rivayet edilen yerin üzerine inşa edilmiştir. Kutsal balıkların olduğu göl ile birlikte Şanlıurfa'nın en önemli ziyaret mekanıdır.",
        history: "Eyyubi döneminde inşa edilmiş, Osmanlı döneminde onarılmıştır. Hz. İbrahim'in Nemrut tarafından ateşe atıldığı ve ateşin göle dönüştüğü rivayet edilen kutsal mekan üzerindedir.",
        features: ["Balıklıgöl Yanında", "Hz. İbrahim Makamı", "Kutsal Mekan", "Eyyubi Dönemi"],
        image: ""
    },
    {
        id: 45,
        name: "Habib-i Neccar Camii",
        city: "Hatay",
        district: "Antakya",
        lat: 36.2021,
        lng: 36.1607,
        period: "Osmanlı",
        year: "Orijinal: 7. yy / Yeniden: 1850'ler",
        architect: "Bilinmiyor",
        style: "Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 1000,
        description: "Anadolu'nun bilinen en eski camisi olan Habib-i Neccar Camii, İslam tarihinde ilk iman eden kişilerden Habib-i Neccar'ın adını taşımaktadır. 2023 Kahramanmaraş depreminde hasar görmüş ve restore edilmiştir.",
        history: "Anadolu'daki ilk cami olduğu kabul edilen yapı, 7. yüzyılda inşa edilmiştir. Habib-i Neccar, Kur'an-ı Kerim'de Yasin Suresi'nde bahsedilen kişi olarak kabul edilmektedir. Çeşitli deprem ve yangınlardan sonra yeniden inşa edilmiştir.",
        features: ["Anadolu'nun En Eski Camisi", "Habib-i Neccar Makamı", "Yasin Suresi'nde Bahsedilen", "Deprem Sonrası Restore"],
        image: ""
    },
    {
        id: 46,
        name: "Ahi Elvan Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9375,
        lng: 32.8600,
        period: "Osmanlı",
        year: "1382",
        architect: "Bilinmiyor",
        style: "Ahi Geleneği / Erken Osmanlı",
        minarets: 1,
        domes: 0,
        capacity: 500,
        description: "Ankara'nın tarihi kalesi yakınında yer alan Ahi Elvan Camii, Ahi teşkilatının Ankara'daki önemini yansıtan bir yapıdır. Ahşap sütunları ve tavan süslemeleriyle dikkat çeker.",
        history: "Ahi Elvan Mehmed Bey tarafından inşa ettirilmiştir. Ahilik geleneğinin Ankara'daki merkezlerinden biri olmuştur. Ahşap iç mimarisi orijinal halini büyük ölçüde korumaktadır.",
        features: ["Ahi Teşkilatı", "Ahşap Sütunlar", "Ankara Kalesi Yakınında", "14. Yüzyıl"],
        image: ""
    },
    {
        id: 47,
        name: "Arslanhane Camii",
        city: "Ankara",
        district: "Altındağ",
        lat: 39.9380,
        lng: 32.8587,
        period: "Selçuklu",
        year: "1289-1290",
        architect: "Bilinmiyor",
        style: "Anadolu Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 800,
        description: "Ankara'nın en eski camilerinden olan Arslanhane Camii, kapısındaki aslan kabartmasından ismini almıştır. Selçuklu ahşap direkli cami geleneğinin Ankara'daki en güzel örneğidir.",
        history: "13. yüzyılda Ahi Şerafettin tarafından inşa ettirilmiştir. Kapısındaki aslan kabartması nedeniyle Arslanhane adıyla anılmaktadır. 24 ahşap sütun üzerinde düz bir çatıya sahiptir.",
        features: ["Aslan Kabartması", "24 Ahşap Sütun", "Selçuklu Ahşap Geleneği", "Ankara'nın En Eski Camisi"],
        image: ""
    },
    {
        id: 48,
        name: "Gazi Husrev Bey Camii Tarzı - Tombul Camii",
        city: "Edirne",
        district: "Merkez",
        lat: 41.6820,
        lng: 26.5480,
        period: "Osmanlı",
        year: "1435",
        architect: "Bilinmiyor",
        style: "Erken Osmanlı",
        minarets: 1,
        domes: 1,
        capacity: 800,
        description: "Edirne'nin tarihi camilerinden biri olup, Osmanlı erken dönem mimarisinin özelliklerini taşımaktadır.",
        history: "15. yüzyılda inşa edilen yapı, Edirne'nin zengin cami mirasının bir parçasıdır.",
        features: ["Erken Osmanlı", "Edirne Tarihi Doku"],
        image: ""
    },
    {
        id: 49,
        name: "Eşrefoğlu Camii",
        city: "Konya",
        district: "Beyşehir",
        lat: 37.6780,
        lng: 31.7260,
        period: "Selçuklu",
        year: "1296-1299",
        architect: "Bilinmiyor",
        style: "Anadolu Selçuklu",
        minarets: 1,
        domes: 0,
        capacity: 1500,
        description: "UNESCO Dünya Mirası Listesi'ndeki Anadolu Selçuklu ahşap direkli camilerinden biri olan Eşrefoğlu Camii, ahşap sütunları ve çini süslemeleriyle Beyşehir'in en önemli yapısıdır.",
        history: "Eşrefoğlu Beyliği'nin kurucusu Eşrefoğlu Süleyman Bey tarafından yaptırılmıştır. 2013 yılında UNESCO Dünya Mirası Listesi'ne dahil edilmiştir. Ahşap direkli Selçuklu camilerinin en büyük ve en iyi korunmuş örneğidir.",
        features: ["UNESCO Dünya Mirası", "Ahşap Sütunlar", "42 Ağaç Direk", "Çini Mihrap"],
        image: ""
    },
    {
        id: 50,
        name: "Battalgazi Ulu Cami",
        city: "Malatya",
        district: "Battalgazi",
        lat: 38.4295,
        lng: 38.3545,
        period: "Selçuklu",
        year: "1224",
        architect: "Bilinmiyor",
        style: "Selçuklu",
        minarets: 1,
        domes: 1,
        capacity: 1500,
        description: "Anadolu Selçuklu devri eserlerinden olan Battalgazi Ulu Cami, spiral tuğla minaresiyle ünlüdür. Malatya'nın eski merkezi Battalgazi'de yer alan yapı, Selçuklu tuğla mimarisinin önemli bir örneğidir.",
        history: "Anadolu Selçuklu döneminde inşa edilmiştir. Spiral tuğla minaresi Anadolu'da nadir görülen bir uygulamadır.",
        features: ["Spiral Tuğla Minare", "Selçuklu Tuğla Mimarisi", "Eski Malatya"],
        image: ""
    }
];
